### ISSUE TITLE
An error occurred while initializing the packages: Unauthorized

### ISSUE THREAD

**Issue by MEIMSGAF** [Nicklason/tf2-automatic#1]
Hello, I have an error  in the system symbol when running automatic.bat (An error occurred while initializing the packages: Unauthorized.), I wanted to know if you can give a guide how to use it or tell me how to solve it please...

**Comment by Nicklason** [comment]
You need access to my pricing api. Only way that you can get that is by paying for it.

**Comment by MEIMSGAF** [comment]
how much?

**Comment by Nicklason** [comment]
It is $500 for lifetime use, or $50 a month.
