### ISSUE TITLE
Screenshot problem

### ISSUE THREAD

**Issue by idinium96** [Nicklason/tf2-automatic#105]
09-04-2019 13:22:46 - warn: Error when capturing and sending screenshot: PhantomJS exited with return value 1

is there anything I can do about this problem?

**Comment by portothree** [comment]
You can fix that by disabling screenshots.
Here's a tutorial made by Cloud#0418 which is fixed on the #help channel on the discord group:
`1. Locate and go to your tf2-automatic folder and open it, go into the folder titled "app" and open "trade.js"
2. Press CTRL+F and search up "screenshot"
3. Comment out every results (if you don't know how to do this, just add // before each line)
4. Now, search "Screenshot .receivedOfferChanged" and copy and paste this into lines 1077-1087
```       
 /*Screenshot.receivedOfferChanged(offer.id, function (err, id) {
           if (err) {
                */Automatic.alert('trade', 'Received offer #' + offer.id + ' (' + offer.partner.getSteamID64() + ') is now marked as ' + TradeOfferManager.ETradeOfferState[offer.state].toLowerCase() + '.');
                /*log.warn('Error when capturing and sending screenshot: ' + err.message);
                log.debug(err.stack);
                return;
            }

            log.debug('Image uploaded, returned id: ' + id);
            Automatic.alert('trade', 'Received offer #' + offer.id + ' (' + offer.partner.getSteamID64() + ') is now marked as ' + TradeOfferManager.ETradeOfferState[offer.state].toLowerCase());
        };*/```
5. Once that is done, search "Screenshot.sentOfferChanged" and copy and paste this into lines 1111-1121
```        /*Screenshot.sentOfferChanged(offer.id, function (err, id) {
            if (err) {
                */Automatic.alert('trade', 'Sent offer #' + offer.id + ' (' + offer.partner.getSteamID64() + ') is now marked as ' + TradeOfferManager.ETradeOfferState[offer.state].toLowerCase() + '.');
                /*log.warn('Error when capturing and sending screenshot: ' + err.message);
                log.debug(err.stack);
                return;
            }

            log.debug('Image uploaded, returned id: ' + id);
            Automatic.alert('trade', 'Sent offer #' + offer.id + ' (' + offer.partner.getSteamID64() + ') is now marked as ' + TradeOfferManager.ETradeOfferState[offer.state].toLowerCase());
        };*/```
6. Now, save the file and close it.
7. Restart your bot and send it a trade offer
8. Hopefully it works and doesn't send a screenshot!`

**Comment by portothree** [comment]
You can fix that by disabling screenshots.
Here's a tutorial made by Cloud#0418 which is fixed on the #help channel on the discord group:
1. Locate and go to your tf2-automatic folder and open it, go into the folder titled "app" and open "trade.js"
2. Press CTRL+F and search up "screenshot"
3. Comment out every results (if you don't know how to do this, just add // before each line)
4. Now, search "Screenshot .receivedOfferChanged" and copy and paste this into lines 1077-1087
```       
 /*Screenshot.receivedOfferChanged(offer.id, function (err, id) {
           if (err) {
                */Automatic.alert('trade', 'Received offer #' + offer.id + ' (' + offer.partner.getSteamID64() + ') is now marked as ' + TradeOfferManager.ETradeOfferState[offer.state].toLowerCase() + '.');
                /*log.warn('Error when capturing and sending screenshot: ' + err.message);
                log.debug(err.stack);
                return;
            }

            log.debug('Image uploaded, returned id: ' + id);
            Automatic.alert('trade', 'Received offer #' + offer.id + ' (' + offer.partner.getSteamID64() + ') is now marked as ' + TradeOfferManager.ETradeOfferState[offer.state].toLowerCase());
        };*/```

5. Once that is done, search "Screenshot.sentOfferChanged" and copy and paste this into lines 1111-1121

```        /*Screenshot.sentOfferChanged(offer.id, function (err, id) {
            if (err) {
                */Automatic.alert('trade', 'Sent offer #' + offer.id + ' (' + offer.partner.getSteamID64() + ') is now marked as ' + TradeOfferManager.ETradeOfferState[offer.state].toLowerCase() + '.');
                /*log.warn('Error when capturing and sending screenshot: ' + err.message);
                log.debug(err.stack);
                return;
            }

            log.debug('Image uploaded, returned id: ' + id);
            Automatic.alert('trade', 'Sent offer #' + offer.id + ' (' + offer.partner.getSteamID64() + ') is now marked as ' + TradeOfferManager.ETradeOfferState[offer.state].toLowerCase());
        };*/```

6. Now, save the file and close it.
7. Restart your bot and send it a trade offer
8. Hopefully it works and doesn't send a screenshot!

**Comment by portothree** [comment]
You can fix that by disabling screenshots.
Here's a tutorial made by Cloud#0418 which is fixed on the #help channel on the discord group:

1. Locate and go to your tf2-automatic folder and open it, go into the folder titled "app" and open "trade.js"
2. Press CTRL+F and search up "screenshot"
3. Comment out every results (if you don't know how to do this, just add // before each line)
4. Now, search "Screenshot .receivedOfferChanged" and copy and paste this into lines 1077-1087

` /*Screenshot.receivedOfferChanged(offer.id, function (err, id) {
           if (err) {
                */Automatic.alert('trade', 'Received offer #' + offer.id + ' (' + offer.partner.getSteamID64() + ') is now marked as ' + TradeOfferManager.ETradeOfferState[offer.state].toLowerCase() + '.');
                /*log.warn('Error when capturing and sending screenshot: ' + err.message);
                log.debug(err.stack);
                return;
            }

            log.debug('Image uploaded, returned id: ' + id);
            Automatic.alert('trade', 'Received offer #' + offer.id + ' (' + offer.partner.getSteamID64() + ') is now marked as ' + TradeOfferManager.ETradeOfferState[offer.state].toLowerCase());
        };*/`

5. Once that is done, search "Screenshot.sentOfferChanged" and copy and paste this into lines 1111-1121

`        /*Screenshot.sentOfferChanged(offer.id, function (err, id) {
            if (err) {
                */Automatic.alert('trade', 'Sent offer #' + offer.id + ' (' + offer.partner.getSteamID64() + ') is now marked as ' + TradeOfferManager.ETradeOfferState[offer.state].toLowerCase() + '.');
                /*log.warn('Error when capturing and sending screenshot: ' + err.message);
                log.debug(err.stack);
                return;
            }

            log.debug('Image uploaded, returned id: ' + id);
            Automatic.alert('trade', 'Sent offer #' + offer.id + ' (' + offer.partner.getSteamID64() + ') is now marked as ' + TradeOfferManager.ETradeOfferState[offer.state].toLowerCase());
        };*/`

6. Now, save the file and close it.
7. Restart your bot and send it a trade offer
8. Hopefully it works and doesn't send a screenshot!

**Comment by portothree** [comment]
You can fix that by disabling screenshots.
Here's a tutorial made by Cloud#0418 which is fixed on the #help channel on the discord group:

`[Unofficial updated guide to disabling screenshots for raspberry pi users or for anyone who just wants to disable screenshots]`

1. Locate and go to your tf2-automatic folder and open it, go into the folder titled "app" and open "trade.js"
2. Press CTRL+F and search up "screenshot"
3. Comment out every results (if you don't know how to do this, just add // before each line)
4. Now, search "Screenshot .receivedOfferChanged" and copy and paste this into lines 1077-1087      
 /*Screenshot.receivedOfferChanged(offer.id, function (err, id) {
           if (err) {
                */Automatic.alert('trade', 'Received offer #' + offer.id + ' (' + offer.partner.getSteamID64() + ') is now marked as ' + TradeOfferManager.ETradeOfferState[offer.state].toLowerCase() + '.');
                /*log.warn('Error when capturing and sending screenshot: ' + err.message);
                log.debug(err.stack);
                return;
            }

            log.debug('Image uploaded, returned id: ' + id);
            Automatic.alert('trade', 'Received offer #' + offer.id + ' (' + offer.partner.getSteamID64() + ') is now marked as ' + TradeOfferManager.ETradeOfferState[offer.state].toLowerCase());
        };*/
5. Once that is done, search "Screenshot.sentOfferChanged" and copy and paste this into lines 1111-1121
       /*Screenshot.sentOfferChanged(offer.id, function (err, id) {
            if (err) {
                */Automatic.alert('trade', 'Sent offer #' + offer.id + ' (' + offer.partner.getSteamID64() + ') is now marked as ' + TradeOfferManager.ETradeOfferState[offer.state].toLowerCase() + '.');
                /*log.warn('Error when capturing and sending screenshot: ' + err.message);
                log.debug(err.stack);
                return;
            }

            log.debug('Image uploaded, returned id: ' + id);
            Automatic.alert('trade', 'Sent offer #' + offer.id + ' (' + offer.partner.getSteamID64() + ') is now marked as ' + TradeOfferManager.ETradeOfferState[offer.state].toLowerCase());
        };*/
6. Now, save the file and close it.
7. Restart your bot and send it a trade offer
8. Hopefully it works and doesn't send a screenshot!

**Comment by portothree** [comment]
You can fix that by disabling screenshots.
Here's a tutorial made by Cloud#0418 which is fixed on the #help channel on the discord group:

https://pastebin.com/YCaxUV0c

**Comment by idinium96** [comment]
Thanks for the tutorial.. but I don't want to disable it actually. I want my bot to be able to capture the trade that they made.

**Comment by Faaa97** [comment]
If you're using raspberry pi, this is what I've done and works fine:

1. Install everything from this section
https://github.com/Nicklason/tf2-automatic/wiki/Setup-on-Linux#phantomjs-installation

2. Either compile it yourself / use pre-compiled binaries
https://github.com/fg2it/phantomjs-on-raspberry/tree/master/rpi-2-3/wheezy-jessie/v2.1.1#phantomjs-on-raspberry-pi-2-and-pi-3wheezy-and-jessie

Then everything works now, but fonts in the image are different from windows version.

If you're not using raspberry pi, try installing PhantomJS for your platform or compile it yourself.

**Comment by Nicklason** [comment]
Removed screenshots in v2
