### ISSUE TITLE
Bot cannot send offer when a weapon include in the payment.

### ISSUE THREAD

**Issue by Eitanoso** [Nicklason/tf2-automatic#106]
The bot cannot send trade offer when a 0.05/weapon include in the payment,
For example, my bot listed a robot part for 1.05, he couldn't send the offer, only for parity numbers of robots part and then weapons won't be included on the trade.
![1243123](https://user-images.githubusercontent.com/47326438/57160379-44c7c700-6df1-11e9-81ee-9fd1d8b3841c.PNG)

**Comment by Nicklason** [comment]
Yes I know I am big sorry - the bot can't send offers with weapons

**Comment by Waflson** [comment]
Duplicate https://github.com/Nicklason/tf2-automatic/issues/246
