### ISSUE TITLE
Bot goes offline and never back online when the connection restarted.

### ISSUE THREAD

**Issue by idinium96** [Nicklason/tf2-automatic#107]
Hello, tf2-automatic community,

The Wi-Fi connection on my laptop is sometimes not stable, which it disconnected and reconnect the network. Surely when the Wi-Fi disconnected, the bot goes Offline, but when it is reconnected, nothing happens (still offline status) until I restart the bot. Are there anyways for the bot to get Online back after the internet goes off? I'm sure you will suggest using cable, but it still the same if something goes wrong with the router.

Thank you.

**Comment by Nicklason** [comment]
I'll need to check this out with the new bot. The new bot should go online when it reconnects.

**Comment by Nicklason** [comment]
It appears that there are no issues with v2 about the bot going offline while running.
