### ISSUE TITLE
Connecting to Steam...

### ISSUE THREAD

**Issue by Yousif2** [Nicklason/tf2-automatic#109]
18:31:38 - info: tf2-automatic v1.12.2 starting
18:31:38 - info: Connecting to Steam...
it's been like this for ages please help

what's the problem here i checked every thing and there is one thing i'm not sure about it is my bp.tf API key 
should i put the http://localhost or the URL of the TF2 automatic?

![Screenshot_1](https://user-images.githubusercontent.com/51090685/58430147-e371db80-80b0-11e9-9c0b-24b5e86df5d0.png)

**Comment by HackerinoS2** [comment]
You need to create a bp.tf API key here: https://backpack.tf/developer/apikey/view

**Comment by Yousif2** [comment]
> You need to create a bp.tf API key here: https://backpack.tf/developer/apikey/view

i created one and i put in the SITE URL: http://localhost
is that right or wrong?
the problem i'm facing is in the pic any suggestions

**Comment by Yousif2** [comment]
here's what's inside automatic file:
18:05:16 - debug: Attempting to connect to PM2...
18:05:18 - debug: Successfully connected to PM2!
18:05:18 - info: tf2-automatic v1.12.2 starting
18:05:18 - info: Connecting to Steam...
18:09:14 - debug: Attempting to connect to PM2...
18:09:14 - debug: Successfully connected to PM2!
18:09:14 - info: tf2-automatic v1.12.2 starting
18:09:14 - info: Connecting to Steam...
18:10:34 - debug: Attempting to connect to PM2...
18:10:34 - debug: Successfully connected to PM2!
18:10:34 - info: tf2-automatic v1.12.2 starting
18:10:34 - info: Connecting to Steam...
18:13:06 - debug: Attempting to connect to PM2...
18:13:06 - debug: Successfully connected to PM2!
18:13:06 - info: tf2-automatic v1.12.2 starting
18:13:06 - info: Connecting to Steam...
18:17:57 - debug: Attempting to connect to PM2...
18:17:57 - debug: Successfully connected to PM2!
18:17:57 - info: tf2-automatic v1.12.2 starting
18:17:57 - info: Connecting to Steam...
18:31:38 - debug: Attempting to connect to PM2...
18:31:38 - debug: Successfully connected to PM2!
18:31:38 - info: tf2-automatic v1.12.2 starting
18:31:38 - info: Connecting to Steam...
19:13:41 - debug: Attempting to connect to PM2...
19:13:41 - debug: Successfully connected to PM2!
19:13:41 - info: tf2-automatic v1.12.2 starting
19:13:41 - info: Connecting to Steam...

**Comment by HackerinoS2** [comment]
Recheck your account.js, make sure everything is fine.

**Comment by Yousif2** [comment]
> Recheck your account.js, make sure everything is fine.

I did double checked it:( (i'm gonna show images of my code edited of course and take a look and tell me what u do u see:)
![Inkedaccount_LI](https://user-images.githubusercontent.com/51090685/58474122-02c14500-8153-11e9-86cd-95f352447317.jpg)
![Inkedconfig 1_LI](https://user-images.githubusercontent.com/51090685/58474123-02c14500-8153-11e9-911e-83f26a857022.jpg)
![Inkedconfig_LI](https://user-images.githubusercontent.com/51090685/58474124-02c14500-8153-11e9-8055-dc2ebc874f07.jpg)

**Comment by HackerinoS2** [comment]
you didn't filled the right input fields, you need to fill these 
![image](https://user-images.githubusercontent.com/39498755/58474244-7eff5c80-8142-11e9-8e28-d963af81db32.png)

**Comment by HackerinoS2** [comment]
Now i recommend you to remove the temp folder and let the bot make those default files again

**Comment by Yousif2** [comment]
alright gonna try it again thanks for ur help <3

**Comment by Yousif2** [comment]
i'm a noob at coding lol so no blame

**Comment by Yousif2** [comment]
problem solved all thanks goes to (HackerinoS2) i hope this will help anyone with 0 code knowledge
