### ISSUE TITLE
I failed to add the item to the pricelist: subscription type does not allow you to use the autopricer

### ISSUE THREAD

**Issue by Yousif2** [Nicklason/tf2-automatic#110]
**Aw sh*t here we go again**
as you see in the title i can't add any items to the bot pricelist the question here is (do i need to upgrade to premium to add items or not because i already paid 1 key for the new Autoprice charges and got 100 charges and i don't know how to use it)
any help would be appreciated <3

*i wanna test the bot and see how everythings works before jumping into premium*

**Comment by Yousif2** [comment]
** also i tried to add the items manually on bp.tf and the bot keep declining offers**

**Comment by HunionKnight** [comment]
Did you add &autoprice=false to the end of your attempt to add the item.

**Comment by Yousif2** [comment]
> Did you add &autoprice=false to the end of your attempt to add the item.

please can you explain in details because i don't know where i can find what u talking about thanks <3

**Comment by HunionKnight** [comment]
Zuus02/10/2019
Examples
 [Without autoprice] 
!add name=The Team Captain&intent=bank&buy_metal=7.44&sell_metal=20l&autoprice=false (you can not autoprice unusuals so you have to add a price and autoprice=false to it)
 [With autoprice] 
!add name=The Team Captain&intent=bank&craftable=false
Adding the Strange Killstreak Australium Rocket Launcher
!add name=The Rocket Launcher&quality=Strange&australium=true&killstreak=1&intent=bank

autoprice= eg. ‘true’ for auto pricing, ‘false’ for non-autopricing (You need permissions to use this. Default is true if not declared).

**Comment by Yousif2** [comment]
> Zuus02/10/2019
> Examples
> [Without autoprice]
> !add name=The Team Captain&intent=bank&buy_metal=7.44&sell_metal=20l&autoprice=false (you can not autoprice unusuals so you have to add a price and autoprice=false to it)
> [With autoprice]
> !add name=The Team Captain&intent=bank&craftable=false
> Adding the Strange Killstreak Australium Rocket Launcher
> !add name=The Rocket Launcher&quality=Strange&australium=true&killstreak=1&intent=bank
> 
> autoprice= eg. ‘true’ for auto pricing, ‘false’ for non-autopricing (You need permissions to use this. Default is true if not declared).

gonna try it and get back with you

**Comment by HunionKnight** [comment]
You'll probably have more luck dealing with these issues in the #help channel of the tf2auto discord. This is where I pulled all this information from [in the pinned messages]

**Comment by Yousif2** [comment]
> You'll probably have more luck dealing with these issues in the #help channel of the tf2auto discord. This is where I pulled all this information from [in the pinned messages]

worked like champ thanks for your help <3
