### ISSUE TITLE
The Wishlist for TF A V.2 explained (Part 1)

### ISSUE THREAD

**Issue by Gobot1234** [Nicklason/tf2-automatic#112]
So I'm gonna preface this with, Nick sucks everything and hasn't put out an update in too long so I'm here to get him motivated to make cool stuff and crush bot.tf

This is part of a larger wishlist, feel free to add more suggestions in the discord #suggestions channel or in the comments or correct me if this is incorrect :)

**Fixing !profit command**

Currently, profit is determined by current key prices stored in your bots listings file. This can be fixed by not dividing by the current key price, but by dividing by the key price at the time of sale and storing that amount, to then call upon.

Eg. If someone makes 45 ref profit (current price of a key at one point) and keys go up to 55 then you suddenly have only Made like 0.8 keys rather than 1 key.

**Comment by Nicklason** [comment]
@Gobot1234 Just make one issue with every fix / feature.

Title of the issue should contain a short title about the fix / feature

Body should contain an explanation
