### ISSUE TITLE
Feature: Fix Profit Calculations

### ISSUE THREAD

**Issue by Gobot1234** [Nicklason/tf2-automatic#113]
So I'm gonna preface this with, Nick sucks everything and hasn't put out an update in too long so I'm here to get him motivated to make cool stuff and crush bot.tf

**Fix profit calculation - not being calculated properly currently**

Currently, profit is determined by current key prices stored in your bots listings file. This can be fixed by not dividing by the current key price, but by dividing by the key price at the time of sale and storing that amount, to then call upon when !profit is typed.

Eg. If someone makes 45 ref profit (current price of a key at one point) and keys go up to 55 then you suddenly have only made like 0.8 keys rather than 1 key.

**Comment by Nicklason** [comment]
Closing because this is about v1
