### ISSUE TITLE
Feature: Add a Minimum Stock Option

### ISSUE THREAD

**Issue by Gobot1234** [Nicklason/tf2-automatic#114]
**Add a minimum stock command - to stop filling your backpack with metal**

At this moment keys are currently 53 refined metal the maximum backpack space is 3000 so you could only have 56 keys in your backpack in metal if you leave this on for just a few hours your backpack will be filled with unwanted metal making it difficult to trade.
 
The easiest fix for this is to add a minimum stock for items so they won’t be sold if you have the amount inputted in the options.

Eg. !add name=Mann Co. Supply Crate Key&min_stock=10
This would stop selling keys if your stock reached 10.

This is a QOL change which makes it easier to trade as having a full backpack makes it very hard to trade.

_This is part of a larger wishlist. Feel free to add more suggestions in the discord #suggestions channel or in the comments or correct me if this is incorrect :)_

**Comment by aethezxd** [comment]
Wouldn't it be max_stock?

**Comment by Gobot1234** [comment]
@aethezxd 
You want to stop selling keys when you have a lower amount in your bp so min_stock works better for keys, it would be max_stock for ref.

**Comment by HunionKnight** [comment]
Completed in v2 tree, @Nicklason can close.
