### ISSUE TITLE
Feature Request: Withdraw/Deposit Commands

### ISSUE THREAD

**Issue by HunionKnight** [Nicklason/tf2-automatic#119]
Withdraw/Deposit commands to help people on mobile.

Example:
[owner] !deposit
[bot] Enter name and amount you wish to deposit
[owner] Refined metal 500
[bot] Sending you an offer to deposit 500 Refined metal.

**Comment by aethezxd** [comment]
Maybe this might be better: `!deposit Refined Metal 50` or `!deposit name=Refined Metal&amount=50`. Let me know what you think about that :D

**Comment by Nicklason** [comment]
It might work better for the admin if it was a cart system.

`!deposit 50 Refined Metal`
`!withdraw 1 Mann Co. Supply Crate Key`

Then you tell the bot that you are done by using `!confirm`.

Either do it like with the prices (for example `!get sku=5021;6`), or do it like with the pricelist commands (`!price 10 Mann Co. Supply Crate Key`).

**Comment by danocmx** [comment]
#202 - Add group tagging for withdraws.

**Comment by Nicklason** [comment]
https://github.com/Nicklason/tf2-automatic/pull/255
