### ISSUE TITLE
Feature Request: Option For Plain Text Trades

### ISSUE THREAD

**Issue by HunionKnight** [Nicklason/tf2-automatic#123]
An alternative option to the screenshot feature.
Bot would output a text overview of the trade instead of generating a screenshot.
May help users running on Pi if screenshots still cause issues.

Example:
[Bot] Trade {Tradenumber} Completed. + 1 x The All-Father | - 7.33 Refined metal

**Comment by Nicklason** [comment]
Done in v2 https://github.com/Nicklason/tf2-automatic/tree/v2
