### ISSUE TITLE
Enhancement Request: Make Uncraftable a Synonym to Non-Craftable

### ISSUE THREAD

**Issue by HunionKnight** [Nicklason/tf2-automatic#125]
Self explanatory request. Submitted solely for the purpose of being tagged and added to the issue tracker.

**Comment by ZeusJunior** [comment]
I dont think 'Non-Craftable' (or 'Uncraftable' for that matter) is used anywhere? Since you use `&craftable=false` in the command

**Comment by Nicklason** [comment]
It is used for the commands price, buy, and sell
