### ISSUE TITLE
Issue you said me to create xD

### ISSUE THREAD

**Issue by AethezxD** [Nicklason/tf2-automatic#13]
5|automati | 26-07-2018 16:23:30 - error: tf2-automatic crashed! Please create an issue with the following log:
5|automati | crash: Automatic.version: 1.7.22; node: v10.7.0 linux x64; Contact: 76561198846789568
5|automati | crash: Stack trace:
5|automati | ReferenceError: community is not defined
5|automati |     at offerAccepted (/bots/tf2-automatic/app/trade.js:1063:5)
5|automati |     at receivedOfferChanged (/bots/tf2-automatic/app/trade.js:986:9)
5|automati |     at handleChangedOffers (/bots/tf2-automatic/app/trade.js:128:9)
5|automati |     at Object.exports.init (/bots/tf2-automatic/app/trade.js:55:5)
5|automati |     at ready (/bots/tf2-automatic/app/client.js:114:11)
5|automati |     at /bots/tf2-automatic/node_modules/async/dist/async.js:3888:9
5|automati |     at /bots/tf2-automatic/node_modules/async/dist/async.js:473:16
5|automati |     at replenish (/bots/tf2-automatic/node_modules/async/dist/async.js:1006:25)
5|automati |     at iterateeCallback (/bots/tf2-automatic/node_modules/async/dist/async.js:995:17)
5|automati |     at /bots/tf2-automatic/node_modules/async/dist/async.js:969:16

**Comment by ZeusJunior** [comment]
This isn't part of the original tf2Automatic code, so making an issue here is kinda useless
