### ISSUE TITLE
Feature Request: Logging Gifts

### ISSUE THREAD

**Issue by Gobot1234** [Nicklason/tf2-automatic#131]
**Log gifts - stores gifts in a separate text file for easy refunds**

Currently gifts aren’t tracked for long periods of time as they are only kept in screenshots, this could be improved by writing to a text file for how much the value of the trade made. This would make refunds easier if someone accidentally sends a gift.

_This is part of a larger wishlist. Feel free to add more suggestions in the discord #suggestions channel or in the comments or correct me if this is incorrect :)_

**Comment by Nicklason** [comment]
I've made it so that you need to include the text "gift" or "donate" in the trade message for the bot to accept it: https://github.com/Nicklason/tf2-automatic/blob/v2/app/handler/trades.js#L564
