### ISSUE TITLE
Feature Request: Donation and Premium Commands for bp.tf

### ISSUE THREAD

**Issue by Gobot1234** [Nicklason/tf2-automatic#132]
**Donations/Premium for backpack.tf**

Donations - The bot sends an offer to the donation bot for how ever many items the owner wants.

**Example**

[owner] !bp.tfdonate 
[bot] What do you want to donate?
[owner] user input (integer, item name)
[bot] That will give you __ extra listings

Premium - The bot does the conversions for how many keys will need to be done for how many months of premium requested.

**Example**

[owner] !bp.tfpremiummon
[bot] How many months of premium of do you want?
[owner] user input (integer)
[bot] that will be __ key(s) are you sure?
[owner] user input (yes/no)
[bot] sends trade offer to the premium bot

or

[owner] !bp.tfpremiumkeys
[bot] How many keys do you want to send to the premium bot?
[owner] user input (integer)
[bot] That will be __ month(s) are you sure?
[owner] user input (yes/no)
[bot] sends trade offer to the premium bot

_This is part of a larger wishlist. Feel free to add more suggestions in the discord #suggestions channel or in the comments or correct me if this is incorrect :)_

**Comment by Nicklason** [comment]
Think there should be a cart for donating and buying premium. That way certain functions can be made, like converting items into dollars, and dollars into listing spaces.
