### ISSUE TITLE
Feature Request: Remove Hidden Listings from Classifieds

### ISSUE THREAD

**Issue by Gobot1234** [Nicklason/tf2-automatic#133]
**Temporarily remove hidden listings from bp.tf**

Currently listings that the user can’t afford wasting classified listings, removing these listings would save on space. This improves the profit a bot can make

_This is part of a larger wishlist. Feel free to add more suggestions in the discord #suggestions channel or in the comments or correct me if this is incorrect :)_

**Comment by DexGunner** [comment]
Please
![20D7175D-FCE4-4C79-834A-A09C98BC031D](https://user-images.githubusercontent.com/61100980/77555032-793bea00-6ebf-11ea-93a4-27d28155cb08.jpeg)
