### ISSUE TITLE
Bot crashed

### ISSUE THREAD

**Issue by Snavellet** [Nicklason/tf2-automatic#135]
My bot crashed, can't respond to commands and trade. Still shows that it's online in pm2 and no logs about its crashing.

**Comment by ZeusJunior** [comment]
Are you 100% sure its not in the logs

**Comment by Snavellet** [comment]
yes

**Comment by Snavellet** [comment]
I did pm2 logs automatic and it only show trade offers.

**Comment by ZeusJunior** [comment]
pm2 log shows error logs seperately. Scroll up and you'll find them

**Comment by Nicklason** [comment]
Closing because inactive. If you still need help then reopen the issue.
