### ISSUE TITLE
Error when when I try to start bot

### ISSUE THREAD

**Issue by RetroIT** [Nicklason/tf2-automatic#136]
Every time I start the bot, it gives me this error: 
An error occurred while initializing the packages: bptf-listings (HTTP error).
I tried the old "delete and re-install" thing but didn't work.
Any ideas?

**Comment by ZeusJunior** [comment]
Have you checked your account / config file? Something is probably wrong with your bptf apikey or bptf token

**Comment by Nicklason** [comment]
Closing because inactive. If you need help then just reopen the issue.
