### ISSUE TITLE
Can i add 2 owners?

### ISSUE THREAD

**Issue by MoltioN1** [Nicklason/tf2-automatic#139]
Hi, 
just asking if i can add 2 owners to the bot?
if yes how?
i have tried in the files over here
![Screenshot_1](https://user-images.githubusercontent.com/56650135/67096410-cd2ffd80-f1c0-11e9-87c2-ba5984e0f730.png)
but is removing the owner option in both accounts.
what can i do so it will work?

ty for your help

**Comment by Gobot1234** [comment]
it doesnt need to be a list

**Comment by Nicklason** [comment]
You forgot to add a comma between the two steamids

**Comment by MoltioN1** [comment]
ty xD
forgot

**Comment by Gobot1234** [comment]
Also ask in the discord server
i need to shut up
