### ISSUE TITLE
Offer sent by the bot too short delay

### ISSUE THREAD

**Issue by LambdAurora** [Nicklason/tf2-automatic#14]
Really???? Only **1 minute**? It's just too short, trade offers when accepted can take up to 3 minutes to be finished?? So when I trade with one of those bots, I accept the trade and randomly it says `OhH nOoOoEs! ThE oFfEr Is No LoNgEr AvAiLaBlE. ReAsOn: ThE oFfEr hAs bEeN aCtIvE fOr A wHiLe.`

It's just super annoying! Please fix this!

**Comment by AethezxD** [comment]
Is it really 1 minute?

**Comment by Nicklason** [comment]
It is a known problem, it will be fixed in v2.
