### ISSUE TITLE
PhantomJS exited with return value 1

### ISSUE THREAD

**Issue by MoltioN1** [Nicklason/tf2-automatic#144]
`Error when capturing and sending screenshot: PhantomJS exited with return value 1`
Does anybody know how to solve it?
i have tried to use these:
```
sudo apt-get update
sudo apt-get install build-essential chrpath libssl-dev libxft-dev
sudo apt-get install libfreetype6 libfreetype6-dev
sudo apt-get install libfontconfig1 libfontconfig1-dev
```
and its not working.
what can i do to solve this?

**Comment by Nicklason** [comment]
Screenshots won't be a thing for the new bot, what you should do is edit the code and disable the screenshots that way. I don't remember the exact lines, but you can look in the pinned messages on the discord server to find them.

**Comment by MoltioN1** [comment]
just asking how would i be able to see the trades?

**Comment by Nicklason** [comment]
> just asking how would i be able to see the trades?

The console ;)

**Comment by MoltioN1** [comment]
but lets say i am not at home?
just asking

**Comment by Nicklason** [comment]
Sorry but that's your problem my dude, I won't be working on the old bot

**Comment by MoltioN1** [comment]
okay ty for your answer and work
