### ISSUE TITLE
Can't configure bot.

### ISSUE THREAD

**Issue by svd201** [Nicklason/tf2-automatic#146]
When i run file "automatic.bat" file for the first time there is error "ReferenceError: primordials is not defined
![error](https://user-images.githubusercontent.com/57662835/68661476-9786f600-056d-11ea-95d0-3eacc6259f17.PNG)

**Comment by ZeusJunior** [comment]
You need to downgrade your node version, v10.16.x

**Comment by Nicklason** [comment]
Zeus's comment is the answer to the problem.
