### ISSUE TITLE
Bot is not listing items on backpack.tf and also says the account is limited

### ISSUE THREAD

**Issue by MoltioN1** [Nicklason/tf2-automatic#148]
So i have a problem with the bot,
he isnt listing items on Backpack.tf
https://prnt.sc/pzmki2
and i have another one sometimes that says the account is limit
http://prntscr.com/pzmn5n
i dont really understand what is going on...

**Comment by MoltioN1** [comment]
i have to say it just started today

**Comment by MoltioN1** [comment]
and now i am getting weird message in the log 
like this: http://prntscr.com/pzmtbg

**Comment by Nicklason** [comment]
When the bot first starts it will say that it has 0 listings on backpack.tf because it removes all of them.

I am not sure about the second error though, your account is either limited, or you can't connect to steam.

**Comment by MoltioN1** [comment]
well if i close and open it again its working and the account is "premium"
so i dont know what is going on

**Comment by Nicklason** [comment]
It is an error that happens sometimes when the bot signs in, if you can trade with the bot then it is working fine.

I am not sure about the listings thought, can you give me the bot's steamid64 or backpack.tf profile link?

**Comment by MoltioN1** [comment]
well now the listings is working.
but like all these weird things happing and some how i just lost 3 keys
idk strange day.

**Comment by Nicklason** [comment]
You lost 3 keys? Ehhh... I am working on a new bot where I fix a lot of the problems the current one has.
