### ISSUE TITLE
InvalidPassword

### ISSUE THREAD

**Issue by mike33460** [Nicklason/tf2-automatic#152]
(https://user-images.githubusercontent.com/58278424/69820126-6a258380-11ce-11ea-9d99-4c61e5b442b3.png)
I've filled out everything in the temp folder, then opened automatic.bat
It gave me this invalid password warning
I presumed it was my steam password so I double checked if it was correct.
It was which was odd so I decided to change my steam password and try again.
Still gave me the warning
Am I missing something? I don't know what to do
Help

**Comment by Nicklason** [comment]
Make sure the username and password are correct

**Comment by mike33460** [comment]
> Make sure the username and password are correct

I rechecked my username and that was the problem.
But now, I've received a login in cooldown 
(https://user-images.githubusercontent.com/58278424/69821685-5d0a9380-11d2-11ea-8627-6569d96f4322.png)
Should I just try again 30 min later?

**Comment by Nicklason** [comment]
Yes, just wait 30-60 minutes
