### ISSUE TITLE
Error after blue screen on my computer.

### ISSUE THREAD

**Issue by idinium96** [Nicklason/tf2-automatic#153]
Hello,
I was running my bot while playing PUBG, it works perfectly fine until today PUBG got an update and crashes every time I run it. Then suddenly my computer goes blue screen, and I constantly get an error message when launching my bot (from automatic.txt file):

> 11-12-2019 14:44:00 - debug: Attempting to connect to PM2...
> 11-12-2019 14:44:00 - debug: Successfully connected to PM2!
> 11-12-2019 14:44:00 - info: tf2-automatic v1.12.4 starting
> 11-12-2019 14:44:00 - info: Connecting to Steam...
> 11-12-2019 14:44:01 - debug: Steam guard code needed
> 11-12-2019 14:44:04 - debug: Setting cookies...
> 11-12-2019 14:44:04 - debug: Initializing tf2-items package.
> 11-12-2019 14:44:04 - debug: Initializing inventory.
> 11-12-2019 14:44:05 - debug: Initializing bptf-listings package.
> 11-12-2019 14:44:05 - error: An error occurred while initializing the packages: bptf-listings (Expected JSON).

I have tried reinstalling the bot by cloning as mentioned in the installation guide (and just paste "account" and "config" JSON file in temp folder), but it still the same.

Need help. Thank you.

**Comment by Nicklason** [comment]
Delete the listings file in the temp folder

**Comment by idinium96** [comment]
> Delete the listings file in the temp folder.
> 
> On a second thought, the error is from when getting listings from bptf. It is bptf not sending JSON back, meaning that bptf might be down.

Thank you for the reply, but for your information, there is no "listings" file in the temp folder in the freshly installed bot.

**Comment by idinium96** [comment]
is there anything I can do?

**Comment by Nicklason** [comment]
> is there anything I can do?

You could debug the bot by editing the code and figurate out why it gives you the error

**Comment by idinium96** [comment]
> On a second thought, the error is from when getting listings from bptf. It is bptf not sending JSON back, meaning that bptf might be down.

Surprisingly. my bot just gets back online after I shut down my computer for a night. I think your second thought was correct.

Thank you for your support.
