### ISSUE TITLE
Auto-Bump for v2?

### ISSUE THREAD

**Issue by JackCapel2314** [Nicklason/tf2-automatic#168]
Same as title it's annoying to rebump 10 things let alone 200, make it toggleable to avoid issues with bumps.

**Comment by Nicklason** [comment]
You can just donate $5 to backpack.tf

**Comment by MatinPlays** [comment]
yes

**Comment by danocmx** [comment]
We're planning on adding user extensions but for now it is a low priority.

**Comment by aethezxd** [comment]
As always you can add it to your bot if you wish but that requires some knowledge of coding with javascript.

**Comment by Nicklason** [comment]
https://github.com/Nicklason/tf2-automatic/pull/250
