### ISSUE TITLE
[Enchantment] Update message sent when offer is active

### ISSUE THREAD

**Issue by confernn** [Nicklason/tf2-automatic#17]
After the new Steam UI rolled out, it would probably be more user-friendly and nicer to replace 

`Automatic.message(offer.partner, 'The offer is now active! You can accept it here: https://steamcommunity.com/tradeoffer/' + offerid + '/');`  @ https://github.com/Nicklason/tf2-automatic/blob/master/app/trade.js#L254 

with 

`Automatic.message(offer.partner, 'The offer is now active! You can accept it by clicking 'View trade offer' above);`

https://gyazo.com/98980338ed4b65cb1b0bfb83657850d1

**Comment by Nicklason** [comment]
I’ll consider doing it when Steam has updated their app
