### ISSUE TITLE
Manually review offers

### ISSUE THREAD

**Issue by Nicklason** [Nicklason/tf2-automatic#174]
For example if the bot detects that a trade may result in a big loss then the bot can ignore the offer. An admin can then review the offer and accept / decline it.

Say someone offers you a duped unusual, mark the offer for review.

Say someone tries to buy a spelled item and the bot doesn’t price spelled differently.

Painted...
Parts...
Craftnumber...

**Comment by idinium96** [comment]
This sounds like a huge improvement.  👍💯

**Comment by lo8888** [comment]
Please do this enhancement, I am waiting to bank more unusual with my bot
