### ISSUE TITLE
Plez do this nick

### ISSUE THREAD

**Issue by AethezxD** [Nicklason/tf2-automatic#18]
}
    else if (message.match("!avatar") && steamID == ownerID) {
        message = message.replace("!avatar ", "");
        var image = message
        community.uploadAvatar(image)
    } 

 } 
    else if (message.match("!name") && steamID == ownerID) {
        message = message.replace("!name ", "");
        var realname = message
        client.setPersona(1, realname)
        var realname = realname.toString();
    } 
to your bot

**Comment by Nicklason** [comment]
I told you to add it yourself...
