### ISSUE TITLE
warn: Failed to create offer because missing buyer pure

### ISSUE THREAD

**Issue by Eitanoso** [Nicklason/tf2-automatic#180]
The bot failed to make an offer for 2 keys exactly although the person had the amount required.

![1](https://user-images.githubusercontent.com/47326438/72084196-bc98aa80-330b-11ea-9e5d-1bdce37698ff.PNG)
Thats a proof that the person had pure keys to pay with.

```0|stevebot  | 2020-01-09 18:06:59 info: Message from VNGE (76561198819752368): !buy Strange Part: Spies Killed
0|stevebot  | 2020-01-09 18:07:00 info: Message sent to VNGE (76561198819752368): Please wait while I process your offer! You will be offered 1 Strange Part: Spies Killed for your 2 keys
0|stevebot  | 2020-01-09 18:07:00 warn: Failed to create offer because missing buyer pure {"requiredCurrencies":{"5021;6":0,"5001;6":null},"sku":"5001;6"}
0|stevebot  | 2020-01-09 18:07:00 info: Message sent to VNGE (76561198819752368): I failed to make the offer. Reason: Something went wrong constructing the offer, try again later.```

**Comment by Nicklason** [comment]
I have seen it a few times now but I still don't know why it does that. I will add more debugging so that I can figure it out.

**Comment by idinium96** [comment]
@Nicklason you need to make revision in app\handler\trades,js file at line 304. The log output is the same.
https://i.imgur.com/s0U8LQ8.png

**Comment by Nicklason** [comment]
@idinium96 It is a generic error I made because it should technically not fail if the constructOffer function worked correctly.

**Comment by Nicklason** [comment]
I added more logging that will make it easier to identify the problem. Please update the bot and give me the logs if you see this warning again.

**Comment by Nicklason** [comment]
https://github.com/Nicklason/tf2-automatic/commit/2c8632d5cb99eb00dfb60b7f4a5edfc22ec9bda6

**Comment by Nicklason** [comment]
![image](https://user-images.githubusercontent.com/21038945/72685955-9800b780-3aef-11ea-8091-02f6e173151e.png)

**Comment by Nicklason** [comment]
It was trying to remove items that it has not picked. That resulted in a NaN value which the bot then sees as not being 0 when creating the offer, so it fails with the error message "Failed to create offer".
