### ISSUE TITLE
Using !restart command causes the bot to go into an infinite login loop

### ISSUE THREAD

**Issue by IceKwibby** [Nicklason/tf2-automatic#184]
When using the !restart command in the chat of your bot, the bot goes into an infinite login loop, whereas shutting down the process doesn't stop the login loop

Using pm2 to run the bot.
https://imgur.com/PZ0LPRY

I'm new to this, sorry if I'm just being stupid >.<

**Comment by Gobot1234** [comment]
PM2 reruns the process by default so shutdown wouldn't work.

**Comment by Nicklason** [comment]
@IceKwibby yeah this is also something I have noticed. PM2 randomly starts a duplicate process when using restart on Windows. I have made an issue so we'll see if someone knows more about it: https://github.com/Unitech/pm2/issues/4567

It might be a problem with the bot and not PM2, but I have had a few problems with PM2 on Windows so I don't know.

**Comment by Nicklason** [comment]
The way you fix it is by using the command `pm2 kill`. This will stop all processes PM2 handles. You then need to start the bot manually.
