### ISSUE TITLE
Error starting the bot

### ISSUE THREAD

**Issue by lo8888** [Nicklason/tf2-automatic#193]
2020-01-10 11:28:29 info: tf2-automatic v2.5.2 is starting...
2|app  | 2020-01-10 11:28:30 info: Setting up pricelist...
2|app  | 2020-01-10 11:28:36 info: Signing in to Steam...
2|app  | 2020-01-10 11:28:36 warn: Waiting 18983 ms before trying to sign in...
2|app  | 2020-01-10 11:28:55 info: Signed in to Steam!
2|app  | 2020-01-10 11:28:55 verbose: Checking account limitations...
2|app  | 2020-01-10 11:28:55 verbose: Account limitation checks completed!
2|app  | 2020-01-10 11:28:56 info: Updating trade offer url on backpack.tf...
2|app  | 2020-01-10 11:28:56 verbose: Signing in to backpack.tf...
2|app  | { Error: Forbidden
2|app  |     at Request.errorHandler (/root/Bots/Unusual/node_modules/@nicklason/request-retry/index.js:113:19)
2|app  |     at Request.retryStrategy (/root/Bots/Unusual/node_modules/@nicklason/request-retry/index.js:49:29)
2|app  |     at Request.<anonymous> (/root/Bots/Unusual/node_modules/requestretry/index.js:133:26)
2|app  |     at Request.self.callback (/root/Bots/Unusual/node_modules/request/request.js:185:22)
2|app  |     at Request.emit (events.js:198:13)
2|app  |     at Request.<anonymous> (/root/Bots/Unusual/node_modules/request/request.js:1161:10)
2|app  |     at Request.emit (events.js:198:13)
2|app  |     at IncomingMessage.<anonymous> (/root/Bots/Unusual/node_modules/request/request.js:1083:12)
2|app  |     at Object.onceWrapper (events.js:286:20)
2|app  |     at IncomingMessage.emit (events.js:203:15) statusCode: 403, body: 'error code: 1006', attempts: 1 }
2|app  | 2020-01-10 11:28:56 error: tf2-automatic crashed! Please create an issue with the following log:
2|app  | package.version: 2.5.2; node: v10.17.0 linux x64}
2|app  | Stack trace:
2|app  | { Error: Forbidden
2|app  |     at Request.errorHandler (/root/Bots/Unusual/node_modules/@nicklason/request-retry/index.js:113:19)
2|app  |     at Request.retryStrategy (/root/Bots/Unusual/node_modules/@nicklason/request-retry/index.js:49:29)
2|app  |     at Request.<anonymous> (/root/Bots/Unusual/node_modules/requestretry/index.js:133:26)
2|app  |     at Request.self.callback (/root/Bots/Unusual/node_modules/request/request.js:185:22)
2|app  |     at Request.emit (events.js:198:13)
2|app  |     at Request.<anonymous> (/root/Bots/Unusual/node_modules/request/request.js:1161:10)
2|app  |     at Request.emit (events.js:198:13)
2|app  |     at IncomingMessage.<anonymous> (/root/Bots/Unusual/node_modules/request/request.js:1083:12)
2|app  |     at Object.onceWrapper (events.js:286:20)
2|app  |     at IncomingMessage.emit (events.js:203:15) statusCode: 403, body: 'error code: 1006', attempts: 1 }
2|app  | 2020-01-10 11:28:56 error: Create an issue here: https://github.com/Nicklason/bot-framework/issues/new
2|app  | 2020-01-10 11:28:56 warn: Exiting...

**Comment by danocmx** [comment]
This seems to be issue with backpack.tf and not the bot directly, error code 1006 and forbidden are coming from backpack.tf, this used to happen because of the instability of the site which is getting fixed at this moment.

**Comment by Nicklason** [comment]
Status code 1006 is from cloudflare: https://support.cloudflare.com/hc/en-us/articles/360029779472-Troubleshooting-Cloudflare-1XXX-errors#error100610071008
