### ISSUE TITLE
Add an !updaterepo command

### ISSUE THREAD

**Issue by ZeusJunior** [Nicklason/tf2-automatic#194]
Just like V1, it'll be much easier to update that way, with the frequent releases.
Can maybe be paired with #75

**Comment by Nicklason** [comment]
@ZeusJunior i have it planned to not be added to the bot, but to a script used to control the bot.

**Comment by Nicklason** [comment]
But I guess it could be added to the restart command as a parameter

**Comment by ZeusJunior** [comment]
To a script?
