### ISSUE TITLE
The bot sent the owner the same offer twice

### ISSUE THREAD

**Issue by Eitanoso** [Nicklason/tf2-automatic#195]
![Capture](https://user-images.githubusercontent.com/47326438/72155372-ae09cc00-33bb-11ea-8ec6-1f33543dffe9.PNG)

**Comment by Nicklason** [comment]
Show us the logs

**Comment by Eitanoso** [comment]
![1](https://user-images.githubusercontent.com/47326438/72155606-1f497f00-33bc-11ea-9ae6-255cbdfba115.PNG)

**Comment by Nicklason** [comment]
I see the problem. I will work on a fix.

**Comment by Nicklason** [comment]
Made a pull request that fixes the issue, closing
