### ISSUE TITLE
Feature Request:  !tag and !withdraw command

### ISSUE THREAD

**Issue by HackerinoS2** [Nicklason/tf2-automatic#202]
Add a command to give a tag to a listing. Example: (!add name=Team Capitan&tag="YourCustomDesiredTag") .

I ask this feature so i can request another one: 

Add a  command that will withdraw all or a specific amount of items that contains a certain tag. Example: !withdraw "YourCustomTagHere" "amount (1, 2, 3... ,all)"

**Comment by aethezxd** [comment]
What would the tags add other than the withdrawal command?

**Comment by Hhanuska** [comment]
It could also be used to update all items with the same tag maybe

**Comment by HackerinoS2** [comment]
Is just like items groups, you can use them for many other things. Gives the bot users the option to customize there own item groups for easier manipulation (intent, prices... etc).

I requested it with the withdraw command because it would be nice to implement and i actually think thats a feature that me and other bot users would use a lot.

**Comment by danocmx** [comment]
#119

**Comment by danocmx** [comment]
Additions direct towards #119
