### ISSUE TITLE
Error getting the item value on trade notification

### ISSUE THREAD

**Issue by lo8888** [Nicklason/tf2-automatic#207]
https://imgur.com/a/KHPRJac

**Comment by Eitanoso** [comment]
![Capture](https://user-images.githubusercontent.com/47326438/72203665-4618bb80-3477-11ea-8f00-0e48a40b5b15.PNG)

**Comment by lo8888** [comment]
https://pastebin.com/nPvtYfnS

Ps. This issue happened in a sent offer

**Comment by lo8888** [comment]
Polldata.json: https://pastebin.com/MPYW9wBr

**Comment by Nicklason** [comment]
https://github.com/Nicklason/tf2-automatic/commit/e6d2c2d52a33e975ec3f5cca3d7d0bc05d8f3986
