### ISSUE TITLE
Save inventory limit

### ISSUE THREAD

**Issue by Nicklason** [Nicklason/tf2-automatic#214]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like**

When the bot starts it should connect to the TF2 GC and wait for the `accountLoaded` event. When the event is emitted, save the inventory limit to a variable.

The inventory limit can be used to figure out if the inventory is almost full. This can be used for https://github.com/Nicklason/tf2-automatic/issues/166 or be an alternative to https://github.com/Nicklason/tf2-automatic/pull/192 (and https://github.com/Nicklason/tf2-automatic/pull/173).

**Describe alternatives you've considered**

**Additional context**

**Comment by ZeusJunior** [comment]
Note
https://github.com/Nicklason/tf2-automatic/blob/master/app/crafting.js#L99
