### ISSUE TITLE
commands.js mod

### ISSUE THREAD

**Issue by cavmit** [Nicklason/tf2-automatic#215]
**Is your feature request related to a problem? Please describe**
There's updates comes out very common so I don't keep up to update and sometimes forget to backup commands.js

**Key thought**
Reference to file to took config from with more priority that commands.js

**Describe the feature you'd like**
It would be very cozy to users to have independent list of commands with high priority of original commands.js
It may be like original commands.js be like template and user's commands.js what doesn't updates and have higher priority than original

**Comment by aethezxd** [comment]
Just back it up before doing a git pull.

**Comment by Nicklason** [comment]
@cavmit you can fork the repository and commit your custom commands to it. When the bot gets updated you can then just pull those changes to your own fork.

**Comment by Nicklason** [comment]
@danocmx will look into it but can't promise anything

**Comment by Waflson** [comment]
Why would you need to backup command.js? Is it because you change the bot's messages? @cavmit

**Comment by cavmit** [comment]
Yes, just a little changes I make. Just didn't knew what fork is for before @Waflson

**Comment by Waflson** [comment]
https://github.com/Nicklason/tf2-automatic/issues/242

Duplicate feature request, closing.

**Comment by danocmx** [comment]
Keep this open for me, thank you.
