### ISSUE TITLE
Handling offer spam

### ISSUE THREAD

**Issue by Waflson** [Nicklason/tf2-automatic#217]
**Describe the bug**
Handling offer #....... spam

**To Reproduce**
No idea

**Expected behavior**
Not spam the Handling offer #......

**Screenshots and logs**
```js
{"message":"Handling offer #3864927979...","level":"verbose","timestamp":"2020-01-11T23:49:10.307Z"}
{"event":"debug","from":"steam-tradeoffer-manager","level":"debug","message":"Error getting trade offers for poll: Timeout","timestamp":"2020-01-11T23:49:10.346Z"}
{"message":"Offer #3864927979 with 76561198922551069 state changed: Active -> InvalidItems","level":"verbose","timestamp":"2020-01-11T23:49:10.628Z"}
{"offer_id":"3864927979","state":8,"finish_time":null,"level":"debug","message":"Took unknown ms to process offer","timestamp":"2020-01-11T23:49:10.641Z"}
{"message":"Handling offer #3864927979...","level":"verbose","timestamp":"2020-01-11T23:49:10.676Z"}
{"message":"Handling offer #3864927979...","level":"verbose","timestamp":"2020-01-11T23:49:10.975Z"}
{"message":"Handling offer #3864927979...","level":"verbose","timestamp":"2020-01-11T23:49:11.232Z"}
```

**Additional context**

Version: 
2.7.0

**Comment by Nicklason** [comment]
The offer state changed to invalid items and the bot then tried to get the offer from the queue. Since the offer is not active it will return null, but since it doens't return anything, it does not get removed from the queue.

https://github.com/Nicklason/tf2-automatic/blob/master/app/trade.js#L610

**Comment by Nicklason** [comment]
https://github.com/Nicklason/tf2-automatic/commit/29783215ef5d5f0b9037918b51e7e7312086a56e
