### ISSUE TITLE
Go through all assetids and check if the item is being sold for a specific price

### ISSUE THREAD

**Issue by danocmx** [Nicklason/tf2-automatic#225]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like**

https://github.com/Nicklason/tf2-automatic/blob/74f813180e98b10443d6092e73287439b113ca7b/app/handler/trades.js#L636
Go through all assetids and check if the item is being sold for a specific price. Sounds like something that should be done in near future.

**Describe alternatives you've considered**

**Additional context**

**Comment by Nicklason** [comment]
Then we need a way to save the price of an item by assetid in the pricelist
