### ISSUE TITLE
Add option to include Discord server invite link in bot's message.

### ISSUE THREAD

**Issue by idinium96** [Nicklason/tf2-automatic#226]
-Add DISCORD_INVITE_LINK in .env or ecosystem.json file.
-Invite link must be the permanent one.
-The invite link (if provided) will appear when there is some problem while the bot is trading with others and also if the trading was a success.
Example:
1. If the bot happens to have some problem (like failed to perform mobile confirmation/not enough pure, etc), instead of sending "Something went wrong while trying to make the offer, try again later!", the bot will now send:
"Something went wrong while trying to make the offer, try again later! You can join our Discord server to ask for help: [link]"
2. After a successful trade is made, instead of "Success! The offer went through successfully.", the bot will now send:
"Success! The offer went through successfully. Join our Discord server! Link: [link]."

**Comment by danocmx** [comment]
Nick is working on socket server that will provide discord webhooks. It will be best if this get's added with the socket server.

**Comment by idinium96** [comment]
Yeah.. true. The discord webhooks will work like #live-trades, and this one for anyone to join the server.

**Comment by ZeusJunior** [comment]
I don’t know if I like people joining for issues related to other people’s bots.
The discord is for tf2automatic support, not your bot support :\
Gonna get questions like “why was my trade declined”

**Comment by danocmx** [comment]
You're always going to get dumb questions that were answered 100 000 times, but there's nothing you can do about it. If you want to add your discord server for this feel free. For now you can use trade message for discord server advertisement.

**Comment by ZeusJunior** [comment]
> I don’t know if I like people joining for issues related to other people’s bots.
> The discord is for tf2automatic support, not your bot support :/
> Gonna get questions like “why was my trade declined”

Follow up to this:
We can not and will not attempt to answer these questions. They should be asked to the bot owner.
If its an issue actually related to tf2automatic he can pass it on in the discord / create an issue

**Comment by idinium96** [comment]
Ok then, instead of "Join our Discord server!", let it be "Join the **owner's** Discord server!".

**Comment by Nicklason** [comment]
Just add the message yourself. Later on we might add custom responses to the config.

**Comment by idinium96** [comment]
Alright, thank you @Nicklason.
