### ISSUE TITLE
A web-only option

### ISSUE THREAD

**Issue by danocmx** [Nicklason/tf2-automatic#227]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like**

Make an env options for the bot to be web only and not use Steam client, yes I know this would be a ton of re-doing stuff and would disable big part of bots features but I feel this could be a way to let users play games while bot is handling offers for various reasons. Just close this if it isn't what the bot strikes to ever be. If so I could atleast make a prototype that would work and make it a branch on this repo so people can easily switch and run if they wanted the bot to just handle trades and play games while doing so.

**Describe alternatives you've considered**

**Additional context**

**Comment by Nicklason** [comment]
I have thought about having one like bptf-automatic where you could run it with your own account and automate it, but I think it would be better if that was a seperate version of the bot.

**Comment by danocmx** [comment]
Well yes sure, but I though about this only when you want to switch between those two versions using same pricelist, logging, env, etc. You would just change one env variable to do so instead of copying number files that will probably increase in the future anyway.
