### ISSUE TITLE
Feature Request: Custom Listings Messages for specific item(s)

### ISSUE THREAD

**Issue by Waflson** [Nicklason/tf2-automatic#228]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like**

From: StarLord 
Custom listings messages for specific items.

**Describe alternatives you've considered**

**Additional context**

**Comment by idinium96** [comment]
@Nicklason @Zeckatz 
![custom listing message](https://user-images.githubusercontent.com/47635037/79858880-ad44f500-8402-11ea-87a6-0bb6ddf61849.PNG)
