### ISSUE TITLE
Ignore decorated weapons when creating buy orders

### ISSUE THREAD

**Issue by ZeusJunior** [Nicklason/tf2-automatic#231]
**Describe the bug**

Currently there are buy orders made by the bot for skins, but due to the bptf api not working for skins a strange Warhawk rocket launcher at 75 keys is listed as a normal strange rocket launcher, for 75 keys.
The prices file prices the strange rocket launcher correctly. The only issue is the listings 

**To Reproduce**
1. Add a skin to your pricelist using the chat commands

**Expected behavior**

Since the api is not designed for skins, the expected behavior and better option would be to ignore them

**Screenshots and logs**

**Additional context**

Version: 2.7.2

**Comment by Nicklason** [comment]
https://github.com/Nicklason/tf2-automatic/commit/2eb07badf6c16f6fc8cc1251ad9c2d8ff6946fbc
