### ISSUE TITLE
Using function in schema that isn't there.

### ISSUE THREAD

**Issue by danocmx** [Nicklason/tf2-automatic#239]
https://github.com/Nicklason/tf2-automatic/blob/da81102507ac3ceebe52192763b9ab9849318c06/app/handler/commands.js#L167 is no longer a function in the schema and requires a fix.

**Describe the bug**

**To Reproduce**

Adding item with an effect.

**Expected behavior**

Adds the item normally.

**Screenshots and logs**

**Additional context**

Version: 
2.7.3

**Comment by ZeusJunior** [comment]
Adding to this
https://github.com/Nicklason/tf2-automatic/blob/da81102507ac3ceebe52192763b9ab9849318c06/app/handler/commands.js#L170 
`item.paintkit` ? 🤔
