### ISSUE TITLE
More Chat Messages Customization

### ISSUE THREAD

**Issue by MatinPlays** [Nicklason/tf2-automatic#242]
Add more customization for e.g. chat commands. You would be able to change the customization in the .Env file!

**Comment by aethezxd** [comment]
This is really unnecessary since you can just change them easily in the commands.js file. You just need a small bit of coding knowledge.

**Comment by Waflson** [comment]
This can be done really easy by any contributor tbh

**Comment by Waflson** [comment]
@MatinPlays Did you have any specific messages you'd like configurable?

**Comment by Waflson** [comment]
https://github.com/Nicklason/tf2-automatic/issues/226

**Comment by MatinPlays** [comment]
Chat Customization's:

- Command Customization e.g. Add more commands easily, change, remove
- The I don't know what you mean Message
- The Trade failed Message
- The Trade Completed Message
- The Confirming Trade Message
- The Sending Trade Message
- ( All possible messages)
