### ISSUE TITLE
Random craftable weapon cost

### ISSUE THREAD

**Issue by cavmit** [Nicklason/tf2-automatic#246]
**Is your feature request related to a problem? Please describe.**
It would be nice to see if you could use random craftable weapon as payment of half a scrap in trade offers you created

**Describe the feature you'd like**
On/off to consider craftable weapon as payment in user's config

**Comment by aethezxd** [comment]
That would be nice indeed.
But maybe adding so the bot automatically converts weapons into scrap would be better?

**Comment by danocmx** [comment]
I believe you're required to accept craft weapons as a payment anyway unless it's a bizarre amount of them, this will get looked at and be done but I cannot promise anything considering the bot's undergoing a rewrite to typescript.
