### ISSUE TITLE
Unexplained crash, see terminal dump.

### ISSUE THREAD

**Issue by RadioQueue** [Nicklason/tf2-automatic#25]
06-08-2018 17:41:33 - error: tf2-automatic crashed! Please create an issue with the following log:
crash: Automatic.version: 1.7.22; node: v8.11.3 linux arm; Contact: 76561198802391456
crash: Stack trace:
{ Error: spawn phantomjs ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn phantomjs',
  path: 'phantomjs',
  spawnargs: 
   [ '/home/pi/tf2-automatic/node_modules/webshot/lib/webshot.phantom.js',
     '{"windowSize":{"width":1024,"height":768},"shotSize":{"width":"window","height":"window"},"shotOffset":{"left":0,"right":0,"top":0,"bottom":0},"streamType":"png","siteType":"url","renderDelay":5000,"quality":75,"cookies":[{"name":"sessionid","value":"f7836757cdeb09f6ee3e3da8","domain":"steamcommunity.com","path":"/"},{"name":"steamLogin","value":"nope","domain":"steamcommunity.com","path":"/"},{"name":"steamLoginSecure","value":"nope","domain":"steamcommunity.com","path":"/"}],"captureSelector":".tradeoffer#tradeofferid_3273133581 .tradeoffer_items_ctn","zoomFactor":1,"settings":{"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"},"onLoadFinished":{"fn":"function () {\\n        var elements = document.getElementsByClassName(\'tradeoffer_items_banner\');\\n        if (elements.length == 0) {\\n            return;\\n        }\\n        var banner = elements[0];\\n\\n        var text = banner.innerHTML;\\n        var digit = text.match(/\\\\d/);\\n        var index = text.indexOf(digit);\\n        if (index == -1) {\\n            return;\\n        }\\n\\n        text = text.substring(0, index);\\n        banner.innerHTML = text;\\n    }","context":{}},"site":"https://steamcommunity.com/profiles/76561198802391456/tradeoffers/?history=1","path":"./images/3273133581.png","streaming":false}' ] }
06-08-2018 17:41:33 - error: Create an issue here: https://github.com/Nicklason/tf2-automatic/issues/new

**Comment by Nicklason** [comment]
You should probably not share your cookies. Other than that, the problem is that you don't have phantomjs installed.
