### ISSUE TITLE
Remove "The" From Unique item listings

### ISSUE THREAD

**Issue by MatinPlays** [Nicklason/tf2-automatic#253]
When using %name% in the environment folder for listing details if the item is unique it would be called "The Killer Exclusive". If the item was strange it would be called "Strange Killer Exclusive". So if the listing was strange the details would say = Buying your "Strange Killer Exclusive". But for unique items the listing would say = Buying your "The Killer Exclusive". Obviously you can see it makes no sense. It would be nice if the bot would remove "The" from unique items so the listings would say = Buying your "Killer Exclusive".

**Comment by danocmx** [comment]
"The" is added by default on unique items in tf2 and thus the naming is accurate to the tf2 schema.

**Comment by MatinPlays** [comment]
Yes I do know but i wanted it to not do that on the listing details. It makes no sense when you read it.
