### ISSUE TITLE
Change logging when admin sends a gift

### ISSUE THREAD

**Issue by danocmx** [Nicklason/tf2-automatic#254]
**Is your feature request related to a problem? Please describe.**

Bot logs a warning when tries to accept offer from owner that was a gift because there's no confirmation required.
**Describe the feature you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Nicklason** [comment]
I am not sure what this issue is about @danocmx @offish ?

**Comment by Nicklason** [comment]
Can this be closed?
