### ISSUE TITLE
Bot has premium - autobump still enabled

### ISSUE THREAD

**Issue by Floyd387** [Nicklason/tf2-automatic#265]
**Describe the bug**
My bot has backpack premium still I get this message in my log:

 warn: Enabling autobump! - Consider paying for backpack.tf premium or donating instead of forcefully autobumping: https://backpack.tf/donate

**To Reproduce**

1. in ecosystem.json option default "AUTOBUMP": true
2. start the bot the usual way
3. console log: 
 warn: Enabling autobump! - Consider paying for backpack.tf premium or donating instead of forcefully autobumping: https://backpack.tf/donate

**Expected behavior**
The bot should automatically disable autobump if it detects bp.tf premium 

Version: 
3.0.0

**Comment by danocmx** [comment]
A fix has been committed, thank you for the right use of bug template!
