### ISSUE TITLE
Trade Acceptance Error

### ISSUE THREAD

**Issue by AlexFrosterTF2** [Nicklason/tf2-automatic#275]
Although im sending "fresh" trades to my bot, i'm receiving the steam 28 trade error.

[![Screenshot from Gyazo]
(https://gyazo.com/1e0485ccd87fc6ab6475bbfd6d8fc091/raw)](https://gyazo.com/1e0485ccd87fc6ab6475bbfd6d8fc091)

**Comment by danocmx** [comment]
https://steamerrors.com/28

**Comment by Nicklason** [comment]
I told him to make an issue because the offer is still not getting accepted even though steam returns that error. I think the bot is not trying to accept mobile confirmation on that error, meaning that the trade will never get accepted.
