### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by AethezxD** [Nicklason/tf2-automatic#28]
3|automati |     at /bots/bot/node_modules/tf2automatic/lib/requests.js:182:9
3|automati |     at Request.<anonymous> (/bots/bot/node_modules/tf2automatic/lib                                                                                                                                                             /api.js:60:9)
3|automati |     at Request._callback (/bots/bot/node_modules/tf2automatic/lib/h                                                                                                                                                             ttp.js:28:26)
3|automati |     at Request.self.callback (/bots/bot/node_modules/tf2automatic/n                                                                                                                                                             ode_modules/request/request.js:185:22)
3|automati |     at Request.emit (events.js:182:13)
3|automati |     at Request.EventEmitter.emit (domain.js:442:20)
3|automati |     at Request.<anonymous> (/bots/bot/node_modules/tf2automatic/nod                                                                                                                                                             e_modules/request/request.js:1157:10)
3|automati |     at Request.emit (events.js:182:13)
3|automati | 08-08-2018 18:38:43 - error: Create an issue here: https://github.c                                                                                                                                                             om/Nicklason/tf2-automatic/issues/new
3|automati | Error: Cannot log onto steamcommunity.com without first being conne                                                                                                                                                             cted to Steam network
3|automati |     at SteamUser.webLogOn (/bots/tf2-automatic-master/node_modules/                                                                                                                                                             steam-user/components/web.js:9:9)
3|automati |     at Object.refreshSession (/bots/tf2-automatic-master/app/automa                                                                                                                                                             tic.js:80:30)
3|automati |     at /bots/tf2-automatic-master/app/trade.js:547:23
3|automati |     at process._tickCallback (internal/process/next_tick.js:68:7)
3|automati | 10-08-2018 13:57:58 - error: An error occurred while initializing t                                                                                                                                                             he packages: tf2-items (Failed to get a valid response).

**Comment by Nicklason** [comment]
You need to send me the whole error.

**Comment by AethezxD** [comment]
I only got that.
