### ISSUE TITLE
Problem with granting owner

### ISSUE THREAD

**Issue by MoltioN1** [Nicklason/tf2-automatic#283]
So i just installed the new bot
and when i am trying to lunch it i am getting this error
http://prntscr.com/qw3w33
when i am deleting the < and >
the bot lunching but i dont have any owner access 

ty for your help

**Comment by MoltioN1** [comment]
and also how can i enable gifts?

**Comment by aethezxd** [comment]
You need to enter the steamid64 in the .env file.
And enabling gifts is not a option that is added yet and will probably never be added.

**Comment by MoltioN1** [comment]
i tried, now i saw it was something else.
ty for your help!
