### ISSUE TITLE
Buy / sell / price items using inventory links

### ISSUE THREAD

**Issue by Nicklason** [Nicklason/tf2-automatic#285]
**Describe the feature you'd like**

Be able to send a message to the bot with the link to the item in the inventory, this can be used for  buying / selling and getting price of item.

https://steamcommunity.com/id/nicklason/inventory/#440_2_4411162577

For example, when using the !buy or !sell command, you can send the link instead of a name and amount.

`!sell https://steamcommunity.com/id/nicklason/inventory/#440_2_4411162577`
`!price https://steamcommunity.com/id/nicklason/inventory/#440_2_4411162577`

**Comment by aethezxd** [comment]
Isn't It just faster to type the name then to go into their inventory and copy link and paste in steam chat?

**Comment by Nicklason** [comment]
> Isn't It just faster to type the name then to go into their inventory and copy link and paste in steam chat?

It is so that you can buy / sell a specific item

**Comment by aethezxd** [comment]
> > Isn't It just faster to type the name then to go into their inventory and copy link and paste in steam chat?
> 
> It is so that you can buy / sell a specific item
> 
> Edit: I should probably have clarified that

Ah okay :)
