### ISSUE TITLE
Error when starting the bot

### ISSUE THREAD

**Issue by lo8888** [Nicklason/tf2-automatic#288]
1|Yan  | 2020-02-14 03:05:20 info: tf2-automatic v3.1.0 is starting...
1|Yan  | SyntaxError: Unexpected token : in JSON at position 2855571
1|Yan  |     at JSON.parse (<anonymous>)
1|Yan  |     at /root/tf2-automatic/dist/app/utils/files.js:32:27
1|Yan  |     at /root/tf2-automatic/node_modules/graceful-fs/graceful-fs.js:115:16
1|Yan  |     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
1|Yan  | 2020-02-14 03:05:21 error: tf2-automatic failed to start properly, this is most likely a 
temporary error. See the log:
1|Yan  | package.version: 3.1.0; node: v10.17.0 linux x64}
1|Yan  | Stack trace:
1|Yan  | SyntaxError: Unexpected token : in JSON at position 2855571
1|Yan  |     at JSON.parse (<anonymous>)
1|Yan  |     at /root/tf2-automatic/dist/app/utils/files.js:32:27
1|Yan  |     at /root/tf2-automatic/node_modules/graceful-fs/graceful-fs.js:115:16
1|Yan  |     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
1|Yan  | 2020-02-14 03:05:21 warn: Exiting...

https://imgur.com/a/iIrYSwm

**Comment by lo8888** [comment]
For some reason it only happens to my item bot, my key bot and the unusual bot is not affected

**Comment by ZeusJunior** [comment]
Delete polldata.json

**Comment by lo8888** [comment]
It works thanks
