### ISSUE TITLE
Add optional params to withdraw & deposit commands.

### ISSUE THREAD

**Issue by aethezxd** [Nicklason/tf2-automatic#289]
**Describe the feature you'd like**
So, I'd like to see some params like stock=true or &amount=all. 
Stock would use all the refined, scrap, reclaimed and keys.
amount=all Would use every count of an item.

**Additional context**
Would ease the current !deposit and !withdraw commands (even though they are super neat) 🤣

**Comment by Nicklason** [comment]
Having it select all on deposit would require the bot to load the inventory of a user and cache it, maybe this can be a new feature.
