### ISSUE TITLE
Improvement on pricing

### ISSUE THREAD

**Issue by lo8888** [Nicklason/tf2-automatic#295]
**Is your feature request related to a problem? Please describe.**
Sometimes the bot selling below buy orders

**Describe the feature you'd like**
A check within the bot or prices.tf that won't sell stuff below bots buy order

**Comment by ZeusJunior** [comment]
Some examples?

**Comment by lo8888** [comment]
https://prices.tf/items/30084;6

**Comment by danocmx** [comment]
Could show classfieds screen shot with this happening?

**Comment by lo8888** [comment]
The market balanced out now. When I created this issue, bots buy orders are higher than the sell orders from most of the bots on backpack.tf
