### ISSUE TITLE
Unable to list specific crate numbers and decorated weapons.

### ISSUE THREAD

**Issue by idinium96** [Nicklason/tf2-automatic#297]
**Your issue may already be reported!**
N/A

**Describe the bug**
- The bot was unable to add listings of specific Mann Co. Supply Crate # (number).
- The bot adds non-existing Mann Co. Supply Crate #'82. 

**To Reproduce**

1. Find the SKU of specific Mann Co. Supply Crate #  (example #1), at marketplace.tf by mouse-over on the item in search and see the link appeared on the left bottom of the browser (if using Chrome).
2. Copy and paste this to bot's steam chat: 
`!add sku=5022;6;c1&min=0&max=1&intent=bank&sell.keys=2&sell.metal=20&buy.keys=1&buy.metal=10`
3. Then try for Mann Co. Supply Crate #'2. 
4. Copy and paste this:
`!add sku=5041;6;c2&min=0&max=1&intent=bank&sell.keys=1&sell.metal=20&buy.keys=0&buy.metal=10`
5. Then try for Mann Co. Supply Crate #'5. 
`!add sku=5045;6;c5&min=0&max=1&intent=bank&sell.keys=0&sell.metal=20&buy.keys=0&buy.metal=1`

**Expected behavior**
-The bot replied for the #'1 crate: 
> Added "Mann Co. Supply Crate #'82".

Crate #'82 does not exist.

-The bot replied for the #'2 crate: 
> Added "Mann Co. Supply Crate #'83".

Crate #'83 does not exist.

-The bot replied for the #'5 crate: 
> Added "Mann Co. Supply Crate #'77".

Crate #'77 does exist, but not what we wanted.

**Screenshots and logs**
![No1](https://user-images.githubusercontent.com/47635037/74907173-cc68db80-53ed-11ea-9345-29562d52a20a.PNG)
![No2](https://user-images.githubusercontent.com/47635037/74920264-dc40e980-5406-11ea-8135-8ce4358d21a3.PNG)
![No5](https://user-images.githubusercontent.com/47635037/74920270-df3bda00-5406-11ea-98d2-f39dae80e4ed.PNG)

**Additional context**
- For Mann Co. Supply Munition #'82, #'83, #'84, #'85, #'90, #'91, #'92 and #'103, it is possible to be added since they all have their own defindex (5734, 5735, 5742, 5752, 5781, 5802, 5803, 5859, respectively).
- I think you should review your [node-tf2-sku](https://github.com/Nicklason/node-tf2-sku)

Version: 
v2.9.5

**Comment by Pocket-Deer** [comment]
Instead of reating a new issue, i want to say, that is the problem with every target items, like: killstreak kits, fabricators, chemistry sets and etc. who have an "additional" number

**Comment by idinium96** [comment]
I've tested in latest version, v3.0.1.
It's work adding the specific crate number to the listings, but unfortunately, the bot did not add any of the added items to bp.tf listing.

Screenshot 1: Successfully added specific crate number:
![crateworks](https://user-images.githubusercontent.com/47635037/75101623-39f94f80-561a-11ea-887c-f0b045c77d9a.PNG)

Screenshot 2: Trying adding crate only with defindex and quality in sku format:
![crateonly](https://user-images.githubusercontent.com/47635037/75101643-7c229100-561a-11ea-9192-b40e258f56f9.PNG)

Screenshot 3: The bot only added to bp.tf the crate without specific number.
![bptf crate](https://user-images.githubusercontent.com/47635037/75101656-bee46900-561a-11ea-85ec-be2da12f6b59.PNG)

**Comment by Pocket-Deer** [comment]
Also the same problem with Killstreak Kits. Whe i trade to bot 2 KKits, they say next:
![image](https://user-images.githubusercontent.com/58855174/75104661-6f179900-563e-11ea-82b7-51664ac3cd4c.png)
And if i try to add it, bot add it succesfully
![image](https://user-images.githubusercontent.com/58855174/75104707-e64d2d00-563e-11ea-92c8-32a0126cdf98.png)
But then when i check the price of that item, bot says he has not that item
![image](https://user-images.githubusercontent.com/58855174/75104721-fbc25700-563e-11ea-8795-8d1ae5dca96b.png)
And he is not create any listings of that.

**Comment by idinium96** [comment]
I think this is why crate failed to be listed. That defindex (5022) is not with the crate series 82 as in value.
@Nicklason 
![crate1](https://user-images.githubusercontent.com/47635037/77045326-ec46eb80-69fb-11ea-9868-c5363987383e.PNG)

**Comment by idinium96** [comment]
![1](https://user-images.githubusercontent.com/47635037/77053557-79dd0800-6a09-11ea-87e0-ecdc37ecf699.PNG)
![weapon](https://user-images.githubusercontent.com/47635037/77053648-a002a800-6a09-11ea-9b96-d5f9c6884eb6.png)

**Comment by idinium96** [comment]
Update for Strangifier:
It only works for sell order listings. Buy order listings will not work.
![sell_listings](https://user-images.githubusercontent.com/47635037/77230127-ff5ce580-6bcc-11ea-85b4-1ec6dc04c403.PNG)
![buy_listings](https://user-images.githubusercontent.com/47635037/77230129-02f06c80-6bcd-11ea-9b71-e29fe658501e.PNG)

**Comment by idinium96** [comment]
Update for Strangifier Chemistry Set, Killstreak Kit (all) and Killstreak Fabricator Kit (both Specialized and Professional):
Able to be added to the pricelist and it only worked for sell order listings.

**Comment by idinium96** [comment]
unstale

**Comment by idinium96** [comment]
Update for Festivized weapon:
Same as the other, it's working to make sell order, but not working for buy order.
[Festivized](https://user-images.githubusercontent.com/47635037/78371838-13f0a300-75fb-11ea-9560-05ed16449602.PNG)

**Comment by Pocket-Deer** [comment]
It is still actual, no? Why are you closed it, bot, please

**Comment by idinium96** [comment]
ignored :(
