### ISSUE TITLE
New v3.0.0 bot declining incoming offers with the right value

### ISSUE THREAD

**Issue by DezGunner** [Nicklason/tf2-automatic#299]
**Describe the bug**

bot declining incoming offers with the right value

**Expected behavior**

Accepting the trade

**Screenshots and logs**

![](https://i.imgur.com/gmCdQkx.png)
![](https://i.imgur.com/X4gycnx.png)
![](https://i.imgur.com/DMto1Kf.png)

Version: 3.0.0

**Comment by aethezxd** [comment]
Doesn't the bot treat weps as 0.66 ref?

**Comment by DezGunner** [comment]
> Doesn't the bot treat weps as 0.66 ref?

in previous versions, the bot accepted such trades

**Comment by IceKwibby** [comment]
Can confirm this happens, not just to weapons, but to the most random stuff.
Both trade offers were the correct price.
![image](https://user-images.githubusercontent.com/59703982/75075265-b77b6d80-54fd-11ea-930e-34ef0a48330b.png)

**Comment by Nicklason** [comment]
https://github.com/Nicklason/tf2-automatic/commit/e936d29a7edd41ec5f2796083003be1eed3699ae
