### ISSUE TITLE
error: An error occurred while initializing the packages: tf2-prices (Unauthorized).

### ISSUE THREAD

**Issue by HackerinoS2** [Nicklason/tf2-automatic#3]
![image](https://user-images.githubusercontent.com/39498755/41507308-1fa2e84e-7228-11e8-9e46-7e2f3e4249c2.png)

**Comment by Waflson** [comment]
You most likely need an API key from Nicklason.

**Comment by HackerinoS2** [comment]
Oh, so the bot is private?

**Comment by Waflson** [comment]
Pretty much. Contact Nicklason if you are looking to purchase it

**Comment by Zulivan** [comment]
The bot is free,
The api is premium.
You need to buy an api key to make the bot work :100:

**Comment by Nicklason** [comment]
Duplicate of #1

**Comment by Jerseyetr** [comment]
Im having this same issue... so you have to purchase the bot?

**Comment by Waflson** [comment]
You need to purchase access to the api
