### ISSUE TITLE
!cancel and !pause command

### ISSUE THREAD

**Issue by Pocket-Deer** [Nicklason/tf2-automatic#304]
**Is your feature request related to a problem? Please describe.**
IT can be very useful, if the bot has a couple commands, which will may be simplify the work with the bot for the user and admin.

**Describe the feature you'd like**
Two new commands:
!cancel (for everyone) - The cancels actual bot's trade offer. Works for user and admin.
!pause (for admins only) - That command will pause the bot works, putting it into the mode "Away" ir "Busy", and leave the non-game app. It can be useful for transferring items to someone (e.g. bptf donate)

**Describe alternatives you've considered**
None alternatives

**Comment by Nicklason** [comment]
I’ll work on cancel offer today, should be easy enough

**Comment by Nicklason** [comment]
I don’t think the pause command would be very useful though

**Comment by aethezxd** [comment]
Instead of !pause you maybe could add !donate.
It would look like this:
!donate name=Max's Severed Head&amount=1
And that would automatically send a trade offer to the backpack.tf donation bot with the correct item and amount.

**Comment by Nicklason** [comment]
> Instead of !pause you maybe could add !donate.
> It would look like this:
> !donate name=Max's Severed Head&amount=1
> And that would automatically send a trade offer to the backpack.tf donation bot with the correct item and amount.

Yes, but I think that there is already an issue for that

**Comment by Nicklason** [comment]
https://github.com/Nicklason/tf2-automatic/issues/132

**Comment by aethezxd** [comment]
Ah ok.

**Comment by Nicklason** [comment]
https://github.com/Nicklason/tf2-automatic/commit/4d4e28a2c55faab86d12982f2202f5eb3e8d6101
https://github.com/Nicklason/tf2-automatic/commit/58e3d2ee1052076450a635452a75a5688d147587
