### ISSUE TITLE
Bot doesn’t remove listings when stops

### ISSUE THREAD

**Issue by DexGunner** [Nicklason/tf2-automatic#305]
**Describe the bug**

Bot doesn’t remove listings when stops

**To Reproduce**

1. Stop the bot
2. Check listings on backpack.tf
3. See that they are not removed

**Expected behavior**

Listings removal

**Screenshots and logs**

![image](https://user-images.githubusercontent.com/61100980/75113521-4ea80880-5657-11ea-85b6-004dba22a876.png)
![](https://i.imgur.com/xkngIa2.png)
![](https://i.imgur.com/WfW2ZJb.png)

Version: 3.0.1

**Comment by Nicklason** [comment]
I can't replicate this. The bot starts and creates the listings, if I use the stop command it will remove the listings and exit.

**Comment by DexGunner** [comment]
> I can't replicate this. The bot starts and creates the listings, if I use the stop command it will remove the listings and exit.

I assume this is a problem with pm2 on Windows. The same problem occurred for a member of the Discord server, @IdiNium, when using the v3.0.1 bot with pm2 on Windows.

**Comment by idinium96** [comment]
Yes. I have no problem when using v3.3.2 with PM2 on Linux (VPS), but PM2 on Windows got this problem.

**Comment by DexGunner** [comment]
![](https://i.imgur.com/WfW2ZJb.png)
