### ISSUE TITLE
[ DevEx ] Run a travis job with linters and tsc on each commit

### ISSUE THREAD

**Issue by lexidor** [Nicklason/tf2-automatic#318]
**Is your feature request related to a problem? Please describe.**

I want to commit with confidence.

**Describe the feature you'd like**

Run all linters and tsc with travis, so you'll get a warning in github when you don't write correct code.

**Describe alternatives you've considered**

None, pick one, circle-ci, travis, jenkins, they're all capable.

**Additional context**

I luv tippusskript.

**Comment by Nicklason** [comment]
I discussed this with @Zelec yesterday and we were talking about GitHub actions.

**Comment by Nicklason** [comment]
https://github.com/Nicklason/tf2-automatic/actions
