### ISSUE TITLE
Bot suddenly stop accepting trades

### ISSUE THREAD

**Issue by Pocket-Deer** [Nicklason/tf2-automatic#322]
**Describe the bug**
For some reason, at some point in time, my incoming trades stopped being accepted and analyzed by the bot. (and by the parallel bots also)
At first, the first trade was not accepted. He simply wrote down all subsequent trades in the logs, but did nothing with them.

**To Reproduce**

1. Actually there are no steps. It just suddenly happened. I attached logs to this issue.

**Expected behavior**
It was expected that on the second incoming trade the bot would start working again and accept trades. But he didn't

**Screenshots and logs**

[2020-02-24.log](https://github.com/Nicklason/tf2-automatic/files/4246026/2020-02-24.log)

Version: 3.0.1

**Comment by CubityFirst** [comment]
Same here, the bot will suddenly see, but not act on any new trades. The log is especially not very helpful aswell ; https://i.cubityfir.st/X2q7CTSQcv.txt

**Comment by lo8888** [comment]
Same issue here. it is not handling incoming trade offers even from the bot owner.

https://imgur.com/a/mKxrRsV

**Comment by idinium96** [comment]
I am not sure, but this log shows that the bot starts ignoring the trade offer after the bot encountered an error.
See **Offer #3925019198** where then it failed to accept.
Then when the bot received the next **Offer #3925022343**, it added to the queue BUT then it says `There are more offers in the queue` and decided not to give offer to handler.
Although the bot encountered an error, the error log file seems empty.
[theman_963-2020-02-27.log](https://github.com/Nicklason/tf2-automatic/files/4259062/theman_963-2020-02-27.log)

**Comment by Nicklason** [comment]
> I am not sure, but this log shows that the bot starts ignoring the trade offer after the bot encountered an error.
> See **Offer #3925019198** where it failed to accept.
> Then when the bot received the next **Offer #3925022343**, it added to the queue BUT then it says `There are more offers in the queue` and decided not to give offer to handler.
> Although the bot encountered an error, the error log file seems empty.
> @Nicklason
> 
> version: 3.3.1
> [theman_963-2020-02-27.log](https://github.com/Nicklason/tf2-automatic/files/4259062/theman_963-2020-02-27.log)

That is exactly what is needed to fix the bug, many thanks.
