### ISSUE TITLE
Bot fails to run - fresh install v. 3.2.0

### ISSUE THREAD

**Issue by Floyd387** [Nicklason/tf2-automatic#327]
**Describe the bug**
After fresh install bot fails to run , version 3.2.0

**To Reproduce**

Following the usual installer instructions for version 3.2.0

**Expected behavior**
Bot should proceed to startup

**Screenshots and logs**
12|dispenser  | 2020-02-25 09:26:27 info: Getting TF2 schema...
12|dispenser  | 2020-02-25 09:26:28 info: Starting bot...
12|dispenser  | SyntaxError: Unexpected end of JSON input
12|dispenser  |     at JSON.parse (<anonymous>)
12|dispenser  |     at new Bot (/home/ned/dispenser/tf2-automatic/dist/classes/Bot.js:74:72)
12|dispenser  |     at async_1.default.eachSeries (/home/ned/dispenser/tf2-automatic/dist/classes/BotManager.js:75:32)
12|dispenser  |     at async_1.default.eachSeries (/home/ned/dispenser/tf2-automatic/dist/classes/BotManager.js:83:17)
12|dispenser  |     at /home/ned/dispenser/tf2-automatic/node_modules/async/dist/async.js:2154:44
12|dispenser  |     at replenish (/home/ned/dispenser/tf2-automatic/node_modules/async/dist/async.js:440:21)
12|dispenser  |     at iterateeCallback (/home/ned/dispenser/tf2-automatic/node_modules/async/dist/async.js:424:21)
12|dispenser  |     at /home/ned/dispenser/tf2-automatic/node_modules/async/dist/async.js:321:20
12|dispenser  |     at tryCatcher (/home/ned/dispenser/tf2-automatic/node_modules/bluebird/js/release/util.js:16:23)
12|dispenser  |     at Promise.successAdapter [as _fulfillmentHandler0] (/home/ned/dispenser/tf2-automatic/node_modules/bluebird/js/release/nodeify.js:22:30)
12|dispenser  |     at Promise._settlePromise (/home/ned/dispenser/tf2-automatic/node_modules/bluebird/js/release/promise.js:601:21)
12|dispenser  |     at Promise._settlePromise0 (/home/ned/dispenser/tf2-automatic/node_modules/bluebird/js/release/promise.js:649:10)
12|dispenser  |     at Promise._settlePromises (/home/ned/dispenser/tf2-automatic/node_modules/bluebird/js/release/promise.js:729:18)
12|dispenser  |     at _drainQueueStep (/home/ned/dispenser/tf2-automatic/node_modules/bluebird/js/release/async.js:93:12)
12|dispenser  |     at _drainQueue (/home/ned/dispenser/tf2-automatic/node_modules/bluebird/js/release/async.js:86:9)
12|dispenser  |     at Async._drainQueues (/home/ned/dispenser/tf2-automatic/node_modules/bluebird/js/release/async.js:102:5)
12|dispenser  | 2020-02-25 09:26:28 error: tf2-automatic failed to start properly, this is most likely a temporary error. See the log:
12|dispenser  | package.version: 3.2.0; node: v10.18.1 linux x64}
12|dispenser  | Stack trace:
12|dispenser  | SyntaxError: Unexpected end of JSON input
12|dispenser  |     at JSON.parse (<anonymous>)
12|dispenser  |     at new Bot (/home/ned/dispenser/tf2-automatic/dist/classes/Bot.js:74:72)
12|dispenser  |     at async_1.default.eachSeries (/home/ned/dispenser/tf2-automatic/dist/classes/BotManager.js:75:32)
12|dispenser  |     at async_1.default.eachSeries (/home/ned/dispenser/tf2-automatic/dist/classes/BotManager.js:83:17)
12|dispenser  |     at /home/ned/dispenser/tf2-automatic/node_modules/async/dist/async.js:2154:44
12|dispenser  |     at replenish (/home/ned/dispenser/tf2-automatic/node_modules/async/dist/async.js:440:21)
12|dispenser  |     at iterateeCallback (/home/ned/dispenser/tf2-automatic/node_modules/async/dist/async.js:424:21)
12|dispenser  |     at /home/ned/dispenser/tf2-automatic/node_modules/async/dist/async.js:321:20
12|dispenser  |     at tryCatcher (/home/ned/dispenser/tf2-automatic/node_modules/bluebird/js/release/util.js:16:23)
12|dispenser  |     at Promise.successAdapter [as _fulfillmentHandler0] (/home/ned/dispenser/tf2-automatic/node_modules/bluebird/js/release/nodeify.js:22:30)
12|dispenser  |     at Promise._settlePromise (/home/ned/dispenser/tf2-automatic/node_modules/bluebird/js/release/promise.js:601:21)
12|dispenser  |     at Promise._settlePromise0 (/home/ned/dispenser/tf2-automatic/node_modules/bluebird/js/release/promise.js:649:10)
12|dispenser  |     at Promise._settlePromises (/home/ned/dispenser/tf2-automatic/node_modules/bluebird/js/release/promise.js:729:18)
12|dispenser  |     at _drainQueueStep (/home/ned/dispenser/tf2-automatic/node_modules/bluebird/js/release/async.js:93:12)
12|dispenser  |     at _drainQueue (/home/ned/dispenser/tf2-automatic/node_modules/bluebird/js/release/async.js:86:9)
12|dispenser  |     at Async._drainQueues (/home/ned/dispenser/tf2-automatic/node_modules/bluebird/js/release/async.js:102:5)
12|dispenser  | 2020-02-25 09:26:28 warn: Exiting...

Version: 
3.2.0

**Comment by Nicklason** [comment]
Alerts option is now an array. See https://github.com/Nicklason/tf2-automatic/releases/tag/v3.0.0 and https://github.com/Nicklason/tf2-automatic/blob/master/ecosystem.template.json#L44.

**Comment by Floyd387** [comment]
Thanks that does it.
