### ISSUE TITLE
Counter offer

### ISSUE THREAD

**Issue by DexGunner** [Nicklason/tf2-automatic#344]
**Is your feature request related to a problem? Please describe.**

No

**Describe the feature you'd like**

Correct the trade and send a counter offer.
Similar to what bot.tf does.

**Comment by menoob003** [comment]
Or, correct the trade and send a counter offer?
similar to what bot.tf does? ;3

Also, most ppl keep their comments friends/private since it gets spammed quickly

**Comment by DexGunner** [comment]
> Or, correct the trade and send a counter offer?
> similar to what bot.tf does? ;3
> 
> Also, most ppl keep their comments friends/private since it gets spammed quickly

Ye, create pls issue, i will close this
