### ISSUE TITLE
Incorrect Error message

### ISSUE THREAD

**Issue by lo8888** [Nicklason/tf2-automatic#345]
**Describe the bug**
Limited bot accounts would have this error showing their backpack is full when someone uses the chat command.

**Screenshots and logs**
https://imgur.com/a/0z4hVLC

**Comment by danocmx** [comment]
This seems like you're having problems with "the" in front of Unique items, correct?

**Comment by lo8888** [comment]
No I mean the bot backpack is not full but the error message is saying its backpack is full.

**Comment by danocmx** [comment]
Ah. Right, sorry. This issue is based off steam.
