### ISSUE TITLE
Bot does not stop when using stop command

### ISSUE THREAD

**Issue by DexGunner** [Nicklason/tf2-automatic#352]
**Describe the bug**
Bot doesn’t remove listings when stops

**To Reproduce**

1. Use pm2 on Windows
2. Stop the bot
3. Check listings on backpack.tf
4. See that they are not removed

**Expected behavior**
Listings removal

**Screenshots and logs**

![00;43;42 - 25 02 2020](https://user-images.githubusercontent.com/61100980/75678070-73befb80-5c95-11ea-8c2a-1d249dea3445.png)
![00;58;15 - 29 02 2020](https://user-images.githubusercontent.com/61100980/75678077-77528280-5c95-11ea-977a-c3f888dd248d.png)
![14;42;36 - 02 03 2020](https://user-images.githubusercontent.com/61100980/75678095-80435400-5c95-11ea-9971-62368f0259d7.png)
![14;44;13 - 02 03 2020](https://user-images.githubusercontent.com/61100980/75678098-820d1780-5c95-11ea-9aac-843035a55f70.png)

Already closed but not fixed issue: https://github.com/Nicklason/tf2-automatic/issues/305

Version: 3.3.3, pm2, Windows

**Comment by Nicklason** [comment]
Don't open a new issue, just reopen the old one

**Comment by Nicklason** [comment]
> Don't open a new issue, just reopen the old one

Didn't know you couldn't reopen an issue if you are not a contributor

**Comment by Nicklason** [comment]
https://github.com/Nicklason/tf2-automatic/issues/305

**Comment by Nicklason** [comment]
The problem is caused by PM2 not telling the process to stop, I'll look for a fix.
