### ISSUE TITLE
Start file

### ISSUE THREAD

**Issue by DexGunner** [Nicklason/tf2-automatic#353]
**Is your feature request related to a problem?.**
No.

**Describe the feature you'd like**
Add "Start" and "Start_pm2" files to start and update bot's environment variables
![15;08;56 - 02 03 2020](https://user-images.githubusercontent.com/61100980/75681546-7e30c380-5c9c-11ea-8c85-20dd1cb575a8.png)

**Comment by aethezxd** [comment]
You can just do it manually, Nicklason does not want unnecessary files.
