### ISSUE TITLE
Trades for weapon

### ISSUE THREAD

**Issue by DexGunner** [Nicklason/tf2-automatic#354]
**Describe the bug**
Bot declines weapons trades without specifying a reason

**To Reproduce**

1. add item to sale for 0.05 ref
2. try to buy it for 1 weapon

**Expected behavior**

**Screenshots and logs**

![20;30;35 - 02 03 2020](https://user-images.githubusercontent.com/61100980/75708617-d500c200-5cc9-11ea-89db-6e890266715f.png)
![20;31;05 - 02 03 2020](https://user-images.githubusercontent.com/61100980/75708625-d8944900-5cc9-11ea-9771-809352c68415.png)
![20;42;44 - 02 03 2020](https://user-images.githubusercontent.com/61100980/75708632-dd58fd00-5cc9-11ea-8343-8a1dee11a7a5.png)

Version: 3.3.3

**Comment by Nicklason** [comment]
The bot does not know what a craft weapon is, but the bot not saying what is wrong will be fixed.
