### ISSUE TITLE
One-time purchase / sale

### ISSUE THREAD

**Issue by DexGunner** [Nicklason/tf2-automatic#366]
**Is your feature request related to a problem?**
No.

**Describe the feature you'd like**

auto_remove=true/false property for buy or sell listings

• true - will remove an item from pricelist after reaching the maximum number of items of a purchase / sale. (intent=buy/sell&auto_remove=true&max=1)
• false (default) - will not remove an item from pricelist

![22;02;21 - 05 03 2020](https://user-images.githubusercontent.com/61100980/76021431-f661e800-5f2d-11ea-9682-c23051708045.png)

**Comment by aethezxd** [comment]
Or maybe just delete all sell intents after 30 days.

**Comment by DexGunner** [comment]
> Or maybe just delete all sell intents after 30 days.

I have needed sell listings like cases, noise makers...

**Comment by idinium96** [comment]
just intent=sell, and it should remove listings made at bp.tf but remain in pricelist.json after the item(s) is sold. If you got another stock then just add it to your bot and it will sell it and remove it again. 🤓

**Comment by DexGunner** [comment]
> just intent=sell, and it should remove listings made at bp.tf but remain in pricelist.json after the item(s) is sold. If you got another stock then just add it to your bot and it will sell it and remove it again. 🤓

The goal is to remove the item from the pricelist, keep it clean.  And you forget what items you added to the pricelist.

**Comment by idinium96** [comment]
Make a list then. Like in excel or something. That's how trading works.
