### ISSUE TITLE
!message command

### ISSUE THREAD

**Issue by kebaburmum** [Nicklason/tf2-automatic#369]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like**

I´d like to see !message being brought back as it was in the older versions, because people keep adding me to ask about pricing and shit. I always used to guide them to write me !message instead of adding me. It was always a neat feature to communicate with people through my bot.
**Describe alternatives you've considered**

**Additional context**

If the offer doesn´t go through 2 times you can make the bot send a message like, having troubles with accepting the offer blablabla, type !help or type !message <your message> to message my owner for additional help.

**Comment by ZeusJunior** [comment]
@Zeckatz is working on it
