### ISSUE TITLE
I got an error, i don't actually understand xde

### ISSUE THREAD

**Issue by Aethezxd** [Nicklason/tf2-automatic#38]
# PLX HELP
1|automatic  | Error: spawn ENOMEM
1|automatic  |     at _errnoException (util.js:992:11)
1|automatic  |     at ChildProcess.spawn (internal/child_process.js:323:11)
1|automatic  |     at Object.exports.spawn (child_process.js:502:9)
1|automatic  |     at Function.spawn (/bots/tf2automatic/node_modules/webshot/node_modules/cross-spawn/index.js:87:19)
1|automatic  |     at spawnPhantom (/bots/tf2automatic/node_modules/webshot/lib/webshot.js:201:32)
1|automatic  |     at spawn (/bots/tf2automatic/node_modules/webshot/lib/webshot.js:105:14)
1|automatic  |     at /bots/tf2automatic/node_modules/webshot/lib/webshot.js:117:16
1|automatic  |     at FSReqWrap.cb [as oncomplete] (fs.js:312:19)
1|automatic  | 08-09-2018 11:33:36 - error: tf2-automatic crashed! Please create an issue with the following log:
1|automatic  | crash: Automatic.version: 1.7.26; node: v8.11.4 linux x64; Contact: 76561198846789568
1|automatic  | crash: Stack trace:
1|automatic  | { Error: spawn ENOMEM
1|automatic  |     at _errnoException (util.js:992:11)
1|automatic  |     at ChildProcess.spawn (internal/child_process.js:323:11)
1|automatic  |     at Object.exports.spawn (child_process.js:502:9)
1|automatic  |     at Function.spawn (/bots/tf2automatic/node_modules/webshot/node_modules/cross-spawn/index.js:87:19)
1|automatic  |     at spawnPhantom (/bots/tf2automatic/node_modules/webshot/lib/webshot.js:201:32)
1|automatic  |     at spawn (/bots/tf2automatic/node_modules/webshot/lib/webshot.js:105:14)
1|automatic  |     at /bots/tf2automatic/node_modules/webshot/lib/webshot.js:117:16
1|automatic  |     at FSReqWrap.cb [as oncomplete] (fs.js:312:19) code: 'ENOMEM', errno: 'ENOMEM', syscall: 'spawn' }

**Comment by Nicklason** [comment]
https://github.com/Nicklason/tf2-automatic/wiki/Setup-on-Linux#phantomjs-installation
