### ISSUE TITLE
Bot wont accept item overpay even if that item is listed in pricelist (with intent=sell)

### ISSUE THREAD

**Issue by idinium96** [Nicklason/tf2-automatic#380]
Your issue may already be reported!
  N/A

**Describe the bug**
  The bot will say it received an offer with an **OVERSTOCKED** _(is taking/offering too many, declining...)_ item, although the item(s) they offered on their side is listed in pricelist (so it's priced) with intent=sell and max=10 (which perhaps the bot will accept it because it is not in the INVALID_ITEMS _(contains items we are not trading (not in pricelist), declining...)_ category.

**To Reproduce**

  1. Add a weapon for the bot to bank (that the bot have, or you deposit it):
(Huntsman) - `!add sku=56;6&min=0&max=1&sell.metal=0.11&buy.metal=0.05&intent=bank`
  2. Add an item with a higher value than a weapon that the bot sell and set it intent to sell:
(Professional's Panama) - `!add sku=109;6&min=0&max=10&intent=sell`
  3. Using another account (not admin), buy (1. - Hunstman) from the bot using (2. - Profesional Panama).
  4. See error/log

**Expected behavior**

  The bot will decline the offer with OVERSTOCKED error.

**Screenshots and logs**

  [Overstocked_log.txt](https://github.com/Nicklason/tf2-automatic/files/4323121/Overstocked_test.txt)
  [pricelist.json for PP](https://user-images.githubusercontent.com/47635037/76503266-88af4200-6480-11ea-8fa6-3892aebd80f7.PNG)

**Additional context**

  I'm using non-released version (review-offers), that's why I can see the error, but I'm sure the latest version (v3.3.8) also have this problem.
Also, I've tried adding this line of code to InventoryManager.ts, but it doesn't seem to be working at all. 
[InventoryManager.ts_overstocked_try](https://user-images.githubusercontent.com/47635037/76513571-77bafc80-6491-11ea-9850-dda265bd695d.PNG)

Version: non-released (review-offers branch - v3.2.1) and latest v3.3.8.

**Comment by Nicklason** [comment]
Can you test it on the latest release?

**Comment by Nicklason** [comment]
Also the steps to reproduce the error are hard to understand. It is a lot "this and that". Just add the steps with a clear description for each step.

**Comment by idinium96** [comment]
> Also the steps to reproduce the error are hard to understand. It is a lot "this and that". Just add the steps with a clear description for each step.

Noted.

> Can you test it on the latest release?

Maybe others can help. If not, I'll send my logs later.

**Comment by idinium96** [comment]
Latest v.3.3.8:
[itemoverpay1](https://user-images.githubusercontent.com/47635037/76598884-bd81ce80-653e-11ea-9e59-8742abdcc571.png)
[overpay_latestversion3.3.8.txt](https://github.com/Nicklason/tf2-automatic/files/4328335/overpay_latestversion3.3.8.txt)

I'm using the same pricelist as the review-offers version, which the Huntsman is intent=bank&max=100 and that Non-Craftable Profesional's Panama is intent=sell&max=10

**Comment by idinium96** [comment]
Here, another case. Since the weapons that this guy put is in the price list will intent=sell, it's been categorized as OVERSTOCKED:
![itemoverpay2_review-offers](https://user-images.githubusercontent.com/47635037/76692944-c8e90d00-6698-11ea-8d83-c5c23e7e1f65.PNG)

**Comment by idinium96** [comment]
Even if the price were not even, if their side contains any items that in our pricelist with intent=sell, it also stated as OVERSTOCKED (not INVALID_VALUE):
![20200315-3](https://user-images.githubusercontent.com/47635037/76701301-febedd80-66fa-11ea-9b92-42c65d747a38.PNG)

**Comment by idinium96** [comment]
Hurmm.. looks like no possible solution about this?

**Comment by Nicklason** [comment]
> Hurmm.. looks like no possible solution about this?

Nah, I just haven't looked into it.

**Comment by NguyenMcRuo** [comment]
Overpay is enabled, pricelist is set up, even with max=20 and 0 in stock the item overpay still gets declined as "Overstocked". Version 3.3.10
![2](https://user-images.githubusercontent.com/62314128/78817860-188ad200-79d4-11ea-8f76-22379b27fc7d.png)
![1](https://user-images.githubusercontent.com/62314128/78817889-23456700-79d4-11ea-8511-219a380941d4.png)
![4](https://user-images.githubusercontent.com/62314128/78817916-2b9da200-79d4-11ea-855a-1eb0388008d3.png)
![3](https://user-images.githubusercontent.com/62314128/78817920-2dfffc00-79d4-11ea-8aa5-e43d23dc8733.png)

**Comment by idinium96** [comment]
![overstocked](https://user-images.githubusercontent.com/47635037/79859243-4bd15600-8403-11ea-9418-412199e2c28f.PNG)
(I am keeping the issue from being labeled as stale...)
