### ISSUE TITLE
!price (bug)

### ISSUE THREAD

**Issue by SlyK10** [Nicklason/tf2-automatic#383]
**Describe the bug**

Hello, I have two graybanns lenses, I use the command, !price graybanns and it only tells me that I don't have any, when they sold me two. It can be a bug or a fault of mine, because when I use it in other cosmetics it works.

**To reproduce**

1.Have graybanns in your inventory
2.Use the command !Price graybanns and you will get the error that you supposedly have no graybanns in your inventory.

**Expected behavior**

That says I have 2/2 graybans

**Screenshots and logs**

https://imgur.com/a/DTzKYUC

**Additional context**

I don't know anything about these topics, I'm using the latest version

**Comment by aethezxd** [comment]
Please follow the bug guidelines, create a new one [here](https://github.com/Nicklason/tf2-automatic/issues/new?assignees=&filename=bug_report.md&labels=bug&title=)

**Comment by idinium96** [comment]
You can try removing and adding it back.

`!remove sku=30104;6` and;
`!add sku=30104;6&max=2`

Then try to check the price again
`!price Graybanns`

**Comment by SlyK10** [comment]
i changed `sku=30104;6` to `name=Graybanns` and works
