### ISSUE TITLE
trying to start bot for the first time, i get a syntax error?

### ISSUE THREAD

**Issue by ZeRedSpy** [Nicklason/tf2-automatic#387]
**Describe the bug**
I followed all the steps on starting the bot, but when i do node dist/app.js i get this exception:
Stack trace:
SyntaxError: Unexpected token o in JSON at position 1
It says it is "probably a temporary error", but it still is broken.

**To Reproduce**

I'm not sure, I seemed to have followed all the steps mentioned...

**Expected behavior**
Bot starts up properly, starts playing tf2-automatic etc.

**Screenshots and logs**
Error log file: \r\npackage.version: 3.3.8; node: v13.9.0 win32 x64}\r\nStack trace:\r\nSyntaxError: Unexpected token o in JSON at position 1\n    at JSON.parse (<anonymous>)\n    at new Bot (C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\dist\\classes\\Bot.js:74:72)\n    at C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\dist\\classes\\BotManager.js:75:32\n    at C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\dist\\classes\\BotManager.js:83:17\n    at C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\node_modules\\async\\dist\\async.js:2159:44\n    at replenish (C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\node_modules\\async\\dist\\async.js:445:21)\n    at iterateeCallback (C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\node_modules\\async\\dist\\async.js:429:21)\n    at C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\node_modules\\async\\dist\\async.js:326:20\n    at tryCatcher (C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise.successAdapter [as _fulfillmentHandler0] (C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\node_modules\\bluebird\\js\\release\\nodeify.js:22:30)\n    at Promise._settlePromise (C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\node_modules\\bluebird\\js\\release\\promise.js:601:21)\n    at Promise._settlePromise0 (C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\node_modules\\bluebird\\js\\release\\promise.js:649:10)\n    at Promise._settlePromises (C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\node_modules\\bluebird\\js\\release\\promise.js:729:18)\n    at _drainQueueStep (C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\node_modules\\bluebird\\js\\release\\async.js:93:12)\n    at _drainQueue (C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\node_modules\\bluebird\\js\\release\\async.js:86:9)\n    at Async._drainQueues (C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\node_modules\\bluebird\\js\\release\\async.js:102:5)","level":"error","timestamp":"2020-03-16T16:29:33.299Z"}

**Additional context**

Version:

**Comment by aethezxd** [comment]
Did you set your alerts to `alerts=['trade']`?

**Comment by ZeRedSpy** [comment]
^ Mine says ALERTS="none"

**Comment by aethezxd** [comment]
Well yeah that's the problem, it should be `ALERTS=["none"]`!

**Comment by ZeRedSpy** [comment]
im trying to run rn

**Comment by ZeRedSpy** [comment]
ah thanks :P
