### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Aethezxd** [Nicklason/tf2-automatic#39]
# Help me ok.
0|bot  | crash: Automatic.version: 1.7.26; node: v8.10.0 linux x64; Contact: 76561198846789568
0|bot  | crash: Stack trace:
0|bot  | { Error: spawn ENOMEM
0|bot  |     at _errnoException (util.js:1022:11)
0|bot  |     at ChildProcess.spawn (internal/child_process.js:323:11)
0|bot  |     at Object.exports.spawn (child_process.js:502:9)
0|bot  |     at Function.spawn (/bots/tf2automatic/node_modules/cross-spawn/index.js:87:19)
0|bot  |     at spawnPhantom (/bots/tf2automatic/node_modules/webshot/lib/webshot.js:201:32)
0|bot  |     at spawn (/bots/tf2automatic/node_modules/webshot/lib/webshot.js:105:14)
0|bot  |     at /bots/tf2automatic/node_modules/webshot/lib/webshot.js:117:16
0|bot  |     at FSReqWrap.cb [as oncomplete] (fs.js:312:19) code: 'ENOMEM', errno: 'ENOMEM', syscall: 'spawn' }

**Comment by Nicklason** [comment]
For future reference, the issue was that he was out of memory on his VPS.

Upgrading it fixed the problem.
