### ISSUE TITLE
Access denied when starting up bot, invalid steam id?

### ISSUE THREAD

**Issue by ZeRedSpy** [Nicklason/tf2-automatic#393]
**Describe the bug**
When I start up the bot, everything is fine until it says "initializing bptf listings", where it says "Unhandled rejection error: access denied", even though im pretty sure I everything in correctly

**To Reproduce**

Not sure

**Expected behavior**
Bot starts up properly

**Screenshots and logs**
here's the error log {"message":"tf2-automatic failed to start properly, this is most likely a temporary error. See the log:\r\npackage.version: 3.3.8; node: v13.9.0 win32 x64}\r\nStack trace:\r\nError: Unknown SteamID input format \"<steamid of person to keep in friendslist>\"\n    at new SteamID (C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\node_modules\\steamid\\index.js:101:9)\n    at C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\dist\\classes\\MyHandler.js:60:22\n    at Array.forEach (<anonymous>)\n    at new MyHandler (C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\dist\\classes\\MyHandler.js:59:27)\n    at new Bot (C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\dist\\classes\\Bot.js:65:24)\n    at C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\dist\\classes\\BotManager.js:75:32\n    at C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\dist\\classes\\BotManager.js:83:17\n    at C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\node_modules\\async\\dist\\async.js:2159:44\n    at replenish (C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\node_modules\\async\\dist\\async.js:445:21)\n    at iterateeCallback (C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\node_modules\\async\\dist\\async.js:429:21)\n    at C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\node_modules\\async\\dist\\async.js:326:20\n    at tryCatcher (C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise.successAdapter [as _fulfillmentHandler0] (C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\node_modules\\bluebird\\js\\release\\nodeify.js:22:30)\n    at Promise._settlePromise (C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\node_modules\\bluebird\\js\\release\\promise.js:601:21)\n    at Promise._settlePromise0 (C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\node_modules\\bluebird\\js\\release\\promise.js:649:10)\n    at Promise._settlePromises (C:\\Users\\The 2nd one\\Desktop\\tf2-automatic\\node_modules\\bluebird\\js\\release\\promise.js:729:18)","level":"error","timestamp":"2020-03-16T16:12:07.723Z"}

**Additional context**

Version: 
latest version

**Comment by Faix-dot** [comment]
i had the same error, in your steam secrets if the the last character is an "=" , remove it;

**Comment by danman5542** [comment]
Hey did you fix this, I'm having the same issue

**Comment by idinium96** [comment]
Join discord server and search for "access denied". You'll find your answer.
