### ISSUE TITLE
Broken queue

### ISSUE THREAD

**Issue by DexGunner** [Nicklason/tf2-automatic#396]
**Describe the bug**

After one error, the queue breaks. The queue stops on an outstanding trade and adds more trades to the queue.

Bot sends to people
> : You are already in the queue! Please wait your turn, there are 19 infront of you.

**To Reproduce**

1. Construct trade offer
2. Get an error sending trade offer (26)
3. Add next trades to the queue

**Screenshots and logs**

[Error sending your trade offer.  Please try again later. (26).txt](https://github.com/Nicklason/tf2-automatic/files/4355334/Error.sending.your.trade.offer.Please.try.again.later.26.txt)

![16;41;36 - 19 03 2020](https://user-images.githubusercontent.com/61100980/77083464-39c85600-6a06-11ea-92c8-d7c8c48c3573.png)
![17;05;43 - 19 03 2020](https://user-images.githubusercontent.com/61100980/77083486-3fbe3700-6a06-11ea-974b-de147ccecdee.png)

Version: 3.3.10

**Comment by DexGunner** [comment]
similar problem, queue breaks after error

![00;54;36 - 22 03 2020](https://user-images.githubusercontent.com/61100980/77260575-8d020900-6c91-11ea-92ee-ca77051653fb.png)
![01;12;28 - 22 03 2020](https://user-images.githubusercontent.com/61100980/77260576-8d020900-6c91-11ea-9a3f-10392ed13b37.png)

**Comment by Hhanuska** [comment]
[queue-breaks.log](https://github.com/Nicklason/tf2-automatic/files/4382091/queue-breaks.log)
Last trade sent on line 9725
Failed to send offer - line 9751
First trade added to broken queue - line 9811

@Nicklason

**Comment by DexGunner** [comment]
![15;18;16 - 04 04 2020](https://user-images.githubusercontent.com/61100980/78450638-bb67e700-7688-11ea-90b0-1084446b7e19.png)
![15;18;48 - 04 04 2020](https://user-images.githubusercontent.com/61100980/78450641-bd31aa80-7688-11ea-9cee-25ef85bf50b6.png)
![15;20;08 - 04 04 2020](https://user-images.githubusercontent.com/61100980/78450643-c02c9b00-7688-11ea-8fdf-07e7f3d3b05b.png)

I get this error almost every 2 days
