### ISSUE TITLE
New property for items

### ISSUE THREAD

**Issue by DexGunner** [Nicklason/tf2-automatic#397]
**Describe the feature you'd like**

Property for items in pricelist to disable listing creation.
So i can easily add weapon banking and weapon listings will not take the place of other items.

**Describe alternatives you've considered**

• Weapon banking

• Make craft weapons a currency
Something like this:
```
If (item_defindex=weapon_defindexes)
Then value=0.05 ref
```

• Change property “enabled” to only disable listings

• A way to keep some items always in the end of pricelist file

[Weapons pricelist](https://pastebin.com/AJbuJPQs)

**Comment by aethezxd** [comment]
``enabled=false`` does that already i believe

**Comment by DexGunner** [comment]
> `enabled=false` does that already i believe

When i tried it, i disables trading for item, not only listings

**Comment by idinium96** [comment]
Yes. `enabled=false` will disabled both listings and trading.
Maybe change the `enabled=false` to only disable listings will help solve this.
