### ISSUE TITLE
Make bot check for bans

### ISSUE THREAD

**Issue by danocmx** [Nicklason/tf2-automatic#398]
**Is your feature request related to a problem? Please describe.**

**Describe the feature you'd like**

Make bot check if bots banned for example for bp being full.
Then notify the owner.

**Describe alternatives you've considered**

**Additional context**

**Comment by Nicklason** [comment]
I think this is a good idea. Can you give an example of what it looks like to get banned? Or maybe we can have @ZeusJunior abuse his power and ban an account so we can test and implement it.
