### ISSUE TITLE
Make pricelist an object instead of an array

### ISSUE THREAD

**Issue by Hhanuska** [Nicklason/tf2-automatic#399]
**Is your feature request related to a problem? Please describe.**
Price updates are painfully slow with any decent sized pricelist and the bot is unresponsive while updating an entry.

**Describe the feature you'd like**
Change the pricelist to an object from an array to improve performance.

**Describe alternatives you've considered**
Alternatively, the pricelist.json file could be kept as an array, so users don't have to remake their pricelist and only convert the pricelist in memory to an array. This way saving to the file would have to be changed, which would make it a bit overcomplicated.

**Additional context**

**Comment by aethezxd** [comment]
I'd suggest mongodb instead. Everyone could get a free mongodb atlas account.
