### ISSUE TITLE
Bot tries to send trade to someone with trade ban

### ISSUE THREAD

**Issue by ghost** [Nicklason/tf2-automatic#40]
[Thats the error log.](https://gyazo.com/c1122fe969c29d193827c4e07bfd6a88).
This wont stop even after restarting vps.
Daddy plox fix.

**Comment by Heaven0220** [comment]
Translation: "(the guy) isnt avaible for trading right now".

**Comment by ZeusJunior** [comment]
#98 ?

**Comment by Nicklason** [comment]
New bot will only retry sending offers a few times before stopping, so this should not be a problem.
