### ISSUE TITLE
Using sell.keys doesn't give the correct value on bp.tf

### ISSUE THREAD

**Issue by TomTruyen** [Nicklason/tf2-automatic#400]
When adding an item like for example 'Bill's Hat' and adding it to the bot using the following line:
_!add name=Bill's Hat&quality=Unique&buy.keys=0&sell.keys=1.73&max=1_
Will make it show on BP.TF (in the preview image) as 1.7 keys. Also it's description says 1.73 keys instead of 1key 39.66 ref

So maybe make it then when I don't specify the sell.metal amount it gets the amount of metal automatically from the sell.keys section. So example: sell.keys=1.73 then the bot will split it into 1 key and 39.66 ref (metal)

Thanks

![Capture](https://user-images.githubusercontent.com/43983832/77227908-e5e37b80-6b83-11ea-8a6a-47c73ae9f420.PNG)

Version: tf2-automatic@3.3.10

**Comment by aethezxd** [comment]
You are supposed to use &sell.keys=1&sell.metal=blabla

**Comment by Hhanuska** [comment]
1.73 keys could be anything from 39.33 to like 40 ref, so it would be better to return an error if sell.keys in not an integer

**Comment by Nicklason** [comment]
It is not really a bug. But now that I think of it, it would be weird to make the bot update the listings, because it would need to update them both when the price of the item changes, but also when the price of keys change.

**Comment by TomTruyen** [comment]
Yea didn't know if I had to place it as bug or not. But I just feel like it should be able to just type 1.73 keys and that the bot auto gets the metal value out of it because otherwise it costs more work to convert to refined metal value and stuff. Though it's not necessary would be great improvement (though only seomething to do when all other things are fixed)
