### ISSUE TITLE
payment offering

### ISSUE THREAD

**Issue by DexGunner** [Nicklason/tf2-automatic#401]
**Describe the feature you'd like**

If a person does not have enough pure, check his inventory for items that the bot is buying and offer to pay using these items. 
For example: MvM ticket or backpack expander, 
craft weapons to pay 0.05 ref / or instead of Scrap (when using craft weapons pricelist)

Maybe using white-list of items to offer

**Comment by aethezxd** [comment]
I don't see why this should be a thing. I feel like this would almost never be used.

**Comment by DexGunner** [comment]
> I don't see why this should be a thing. I feel like this would almost never be used.

If a person does not have enough pure or to construct offers with 0.05 ref

**Comment by aethezxd** [comment]
This would add like 1 trade to every 1k trades. Personally It's not worth the time it takes.

**Comment by DexGunner** [comment]
> This would add like 1 trade to every 1k trades. Personally It's not worth the time it takes.

there are more than 1 / 1k of such unfinished trades + this will speed up the replenishment of the stock of items that the bot is buying, it will be as an automatic advertisement

**Comment by aethezxd** [comment]
Indeed there are more but not everyone of those "unfinished" trades will want to offer that or even has those kinds of items. Like I said it's not worth the time it takes to code this.

**Comment by DexGunner** [comment]
> Indeed there are more but not everyone of those "unfinished" trades will want to offer that or even has those kinds of items. Like I said it's not worth the time it takes to code this.

ok, sorry for wasting time
