### ISSUE TITLE
Automatically Disable Buy Order That Needs More Metal/Keys

### ISSUE THREAD

**Issue by luigia** [Nicklason/tf2-automatic#403]
**Describe the feature you'd like**
Automatically disable buy orders that lack sufficient currency. After the bot gains enough metal or keys for that buy order, re-enable the buy order.

**Describe alternatives you've considered**
Manually disable each individual buy order that the bot does not have enough currency for in the `pricelist.json` file.

**Additional context**
Sometimes the bot won't have enough keys or metal for a certain buy order. The listing will remain hidden until the bot has sufficient currency. However, this takes up classified listings slots as well. A solution would be to disable those buy orders and enable them when the bot can actually buy the item.

<img width="475" alt="image" src="https://user-images.githubusercontent.com/4554967/77556390-d79ca480-6e8e-11ea-869c-673f2935f275.png">

**Comment by Nicklason** [comment]
I guess the bot could remove buy orders if it reached the listing cap and has items to sell. This is only really a problem if you have more items in the pricelist than you have listings, but the bot could be made so that when you add new items to the pricelist that you want to sell then the bot will remove buy orders.

**Comment by aethezxd** [comment]
The easy solution to this is actually donating to backpack.tf.

**Comment by DexGunner** [comment]
> The easy solution to this is actually donating to backpack.tf.

it isnt solution for this problem, it wasting money, you must pay for wasted listings

**Comment by DexGunner** [comment]
> I guess the bot could remove buy orders if it reached the listing cap and has items to sell. This is only really a problem if you have more items in the pricelist than you have listings, but the bot could be made so that when you add new items to the pricelist that you want to sell then the bot will remove buy orders.

Will the bot remove buy orders for which there is not enough currency if it reaches the listing cap and there are still items in the pricelist for which there is enough currency to buy?
