### ISSUE TITLE
Remove entire pricelist

### ISSUE THREAD

**Issue by TheProcave** [Nicklason/tf2-automatic#404]
Is your feature request related to a problem? Please describe.
No.

Describe the feature you'd like
Remove the entire pricelist, to make it easier to remove all prices.

Describe alternatives you've considered
/

Additional context
Kind regards,
Procave

**Comment by aethezxd** [comment]
Easier solution instead of coding one.

1. Replace the pricelist.json's contents with `[]`

Done :) enjoy!

**Comment by DexGunner** [comment]
or just delete pricelist.json
