### ISSUE TITLE
Automatically sell a Key when the bot has less than x Refined Metal in it's inventory

### ISSUE THREAD

**Issue by HumbleUsername** [Nicklason/tf2-automatic#405]
**Is your feature request related to a problem? Please describe.**
My bot and I assume others are in constant need of refined metal, I need to refill it daily with 1000+ metal

**Describe the feature you'd like**
I'd like for the bot to sell a key to the highest backpack.tf buyorder when it has under x metal

**Describe alternatives you've considered**

**Additional context**

**Comment by Waflson** [comment]
under x metal => list sell order for key 
over x metal => list buy order for key

x configurable on config file

**Comment by HumbleUsername** [comment]
Only issue with that is having sell/buy order means you could be waiting potentially hours for the metal/keys to be traded. Whereas if you make the bot send the offer you'll have it instantly~

**Comment by DexGunner** [comment]
Yes, please
![](https://i.imgur.com/zrX7FHc.png)

**Comment by DexGunner** [comment]
______________________________________________________________________________
>	ecosystem.jsonᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠ⎯ ❐ ⤬
```
                "MINIMUM_REFINED": 50,
                "MAXIMUM_REFINED": 125,
```



______________________________________________________________________________
>	MyHandler.tsᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠᅠ⎯ ❐ ⤬

lines 53+
```
        const minimumRefined = parseInt(process.env.MINIMUM_REFINED);
        const maximumRefined = parseInt(process.env.MAXIMUM_REFINED);	

        if (!isNaN(minimumRefined)) {
            this.minimumRefined = minimumRefined;
        }

        if (!isNaN(maximumRefined)) {
            this.maximumRefined = maximumRefined;
        }

```



lines 924+
```
        const minRefined = this.minimumRefined
        const maxRefined = this.maximumRefined

		if (refined < minRefined) {
            intent=sell FOR KEYS
        },
		if (refined > maxRefined) {
            intent=buy FOR KEYS
		}
```



### I don't know how to change intent with code, so, maybe someone could finish it
