### ISSUE TITLE
Does not check admin list before removing friends

### ISSUE THREAD

**Issue by Waflson** [Nicklason/tf2-automatic#406]
**Describe the bug**

Does not check if its an admin before removing friend.
https://github.com/Nicklason/tf2-automatic/blob/31269a184a6b9001f0621b84698c5b3f39e751b2/src/classes/MyHandler.ts#L766

**Expected behavior**

Check both admin list and friendsToKeep list

**Comment by mabdu11ah** [comment]
Surely the admin should also put their SID64 in the `KEEP` value in `template.env`?
