### ISSUE TITLE
tf2-automatic failed to start properly

### ISSUE THREAD

**Issue by Pianissimo7** [Nicklason/tf2-automatic#419]
i set up the bot 2 days ago and all was good, until today's morning when my computer restarted and the bot decided to not run anymore and gave me and error in the command prompt when i tried to run it.
this is the error i got when trying to run the bot:
![TradeBotError (2)](https://user-images.githubusercontent.com/62753869/79127791-2c0ab400-7dab-11ea-8175-3a6415c6e457.png)

**Comment by HEYM8PT** [comment]
Did you tried to run it with the PM2

**Comment by Pianissimo7** [comment]
> 
> 
> Did you tried to run it with the PM2

isnt that the server that you need to buy? if yes then i did not, im trying not to pay for running the bot and instead run it on my own computer since i leave it open 24/7 anyways

**Comment by idinium96** [comment]
You can try delete the `polldata.json` file found in your tf2-automatic files folder.
./tf2-automatic/files/{steamusername}/polldata.json

Delete that file and try again. If it's fixed, it's likely that your polldata.json is corrupted.

**Comment by Pianissimo7** [comment]
> 
> 
> You can try to delete the `polldata.json` file found in your tf2-automatic files folder.
> ./tf2-automatic/files/{steamusername}/polldata.json
> 
> Delete that file and try to run the bot again. If it's fixed, it's likely that your polldata.json is corrupted.

it worked, thanks alot.
