### ISSUE TITLE
Duplication check

### ISSUE THREAD

**Issue by lo8888** [Nicklason/tf2-automatic#421]
**Describe the bug**
The bot accepts the duped item without asking manual review. 

**Screenshots and logs**
https://i.imgur.com/nO4KPo3.png - the log
https://backpack.tf/item/2111219510 - The hat

Version: v3.4.0

**Comment by lo8888** [comment]
I switch the admin to my other bots so it won't accept because I am the admin

**Comment by Nicklason** [comment]
The bot didn’t do a dupe check on the item. Make sure that you have enabled dupe checks and check your minimum key value for the dupe checks, I think that’s what is wrong.

**Comment by lo8888** [comment]
Where to enable dupe check? Ecosystem.json?

**Comment by lo8888** [comment]
I see. My ecosystem.json file is outdated.

**Comment by lo8888** [comment]
Where do I set the minimum key value for dupe checks?

**Comment by lo8888** [comment]
Also, it doesn't work when users use chat command, eg !sell Stormy Storm Slick Cut, as the bot will send the trade offer to the user.

**Comment by idinium96** [comment]
Well... you're not using the `dupe-check` branch... that's because I see your log there's no such:
`... checking 1 item for dupes...`
`Dupe checking #assetid`
`bla bla...`

FYI, the duped check feature is still not in the branch master yet. If you want to try this feature, open cmd and navigate to your bot folder and type in the command `git checkout dupe-check`, update your `.env` or `ecosystem.json` and you'll have dupes check feature enabled.

**Comment by Nicklason** [comment]
https://github.com/Nicklason/tf2-automatic/pull/420

**Comment by lo8888** [comment]
I just test that again with the version with dupe checks and it is still not working. Both received and sent ones.

Here's the log:
Receives offer: https://i.imgur.com/kutPizh.png
Sends offer: https://i.imgur.com/YsBodWa.png

I am still testing with the old duped hat I mentioned above.

**Comment by Nicklason** [comment]
You’re running v3.3.13?

**Comment by lo8888** [comment]
Yes

**Comment by idinium96** [comment]
Sad. It's v3.5.0 now. This version have duped check feature. Please update it now and try it again.

**Comment by lo8888** [comment]
Retry with v3.5.0 but it still accepts the offer.

https://i.imgur.com/0XmXxwU.png

**Comment by idinium96** [comment]
Huuurrmmm for some reason, it skips some step.
@Nicklason
