### ISSUE TITLE
Stopped relisting offers after mobile confirmation failed.

### ISSUE THREAD

**Issue by arik123** [Nicklason/tf2-automatic#423]
**Describe the bug**
Bot stopped relisting offers after mobile confirmation failed. Probably caused by steam being down.

**Screenshots and logs**
`{"message":"Offer #3995218828 from 76561198087242027 received offer","level":"info","timestamp":"2020-04-14T16:01:22.360Z"}
{"message":"Added offer to queue","level":"debug","timestamp":"2020-04-14T16:01:22.362Z"}
{"message":"Only offer in queue, process it","level":"debug","timestamp":"2020-04-14T16:01:22.362Z"}
{"message":"Giving offer to handler","level":"debug","timestamp":"2020-04-14T16:01:22.362Z"}
{"message":"Offer #3995218828 from 76561198087242027 is being processed...","level":"info","timestamp":"2020-04-14T16:01:22.363Z"}
{"message":"Offer #3995218828 from 76561198087242027 checking escrow...","level":"info","timestamp":"2020-04-14T16:01:22.367Z"}
{"message":"Checking escrow","level":"debug","timestamp":"2020-04-14T16:01:22.367Z"}
{"message":"Attempting to check escrow...","level":"debug","timestamp":"2020-04-14T16:01:22.368Z"}
{"message":"Escrow callback","level":"debug","timestamp":"2020-04-14T16:01:23.994Z"}
{"message":"Done checking escrow","level":"debug","timestamp":"2020-04-14T16:01:23.994Z"}
{"message":"Offer #3995218828 from 76561198087242027 checking bans...","level":"info","timestamp":"2020-04-14T16:01:23.995Z"}
{"message":"Offer #3995218828 from 76561198087242027 accepting. Summary:\nAsked: 2.5 ref (Battle-Worn Robot Money Furnace x3)\nOffered: 2.66 ref (Refined Metal x2, Reclaimed Metal, Scrap Metal x3)","level":"trade","timestamp":"2020-04-14T16:01:24.206Z"}
{"message":"Offer #3995218828 from 76561198087242027 handler is done with offer","level":"debug","timestamp":"2020-04-14T16:01:24.207Z"}
{"message":"Offer #3995218828 from 76561198087242027 successfully accepted; confirmation required","level":"trade","timestamp":"2020-04-14T16:01:27.486Z"}
{"offerId":"3995218828","level":"debug","message":"Accepting mobile confirmation...","timestamp":"2020-04-14T16:01:27.487Z"}
{"message":"Offer #3995218828 from 76561198087242027 done doing action on offer","level":"debug","timestamp":"2020-04-14T16:01:27.490Z"}
{"message":"Processing next offer","level":"debug","timestamp":"2020-04-14T16:01:27.490Z"}
{"message":"Already processing offer or queue is empty","level":"debug","timestamp":"2020-04-14T16:01:27.490Z"}
{"level":"debug","message":"Error while trying to accept mobile confirmation: Při načítání stránky s potvrzením došlo k chybě. Zkuste to znovu později.","stack":"Error: Při načítání stránky s potvrzením došlo k chybě. Zkuste to znovu později.\n    at /home/arik123max/tf2-automatic/node_modules/steamcommunity/components/confirmations.js:33:14\n    at SteamCommunity.<anonymous> (/home/arik123max/tf2-automatic/node_modules/steamcommunity/components/confirmations.js:276:3)\n    at Request._callback (/home/arik123max/tf2-automatic/node_modules/steamcommunity/components/http.js:67:15)\n    at Request.self.callback (/home/arik123max/tf2-automatic/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:315:20)\n    at Request.<anonymous> (/home/arik123max/tf2-automatic/node_modules/request/request.js:1161:10)\n    at Request.emit (events.js:315:20)\n    at Gunzip.<anonymous> (/home/arik123max/tf2-automatic/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:421:28)\n    at Gunzip.emit (events.js:327:22)\n    at endReadableNT (_stream_readable.js:1201:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","timestamp":"2020-04-14T16:01:28.034Z"}
{"message":"1 incoming offer (0 on hold), 0 outgoing offers (0 on hold)","level":"verbose","timestamp":"2020-04-14T16:01:31.223Z"}
{"message":"Checking account info","level":"debug","timestamp":"2020-04-14T16:02:00.802Z"}
{"message":"Checking account info","level":"debug","timestamp":"2020-04-14T16:03:31.733Z"}
{"statusCode":502,"body":"<html>\n<head><title>502 Bad Gateway</title></head>\n<body bgcolor=\"white\">\n<center><h1>502 Bad Gateway</h1></center>\n<hr><center>nginx/1.14.0 (Ubuntu)</center>\n</body>\n</html>\n","attempts":1,"level":"warn","message":"Failed to  get account info from backpack.tf: Expected JSON","stack":"Error: Expected JSON\n    at Request.retryStrategy (/home/arik123max/tf2-automatic/node_modules/@nicklason/request-retry/index.js:37:15)\n    at Request.<anonymous> (/home/arik123max/tf2-automatic/node_modules/requestretry/index.js:133:26)\n    at Request.self.callback (/home/arik123max/tf2-automatic/node_modules/request/request.js:185:22)\n    at Request.emit (events.js:315:20)\n    at Request.<anonymous> (/home/arik123max/tf2-automatic/node_modules/request/request.js:1161:10)\n    at Request.emit (events.js:315:20)\n    at IncomingMessage.<anonymous> (/home/arik123max/tf2-automatic/node_modules/request/request.js:1083:12)\n    at Object.onceWrapper (events.js:421:28)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (_stream_readable.js:1201:12)\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)","timestamp":"2020-04-14T16:03:31.796Z"}
{"message":"Removing all listings","level":"debug","timestamp":"2020-04-14T16:03:37.425Z"}
{"message":"Checking listings...","level":"debug","timestamp":"2020-04-14T16:03:37.425Z"}
{"message":"Count didn't change","level":"debug","timestamp":"2020-04-14T16:03:37.652Z"}
{"message":"Removing all listings...","level":"debug","timestamp":"2020-04-14T16:03:37.652Z"}
{"message":"Checking listings...","level":"debug","timestamp":"2020-04-14T16:03:37.725Z"}
{"message":"1 incoming offer (0 on hold), 0 outgoing offers (0 on hold)","level":"verbose","timestamp":"2020-04-14T16:04:02.430Z"}
{"message":"Checking account info","level":"debug","timestamp":"2020-04-14T16:05:00.775Z"}
{"message":"Checking account info","level":"debug","timestamp":"2020-04-14T16:06:30.777Z"}
{"message":"1 incoming offer (0 on hold), 0 outgoing offers (0 on hold)","level":"verbose","timestamp":"2020-04-14T16:06:36.357Z"}
{"message":"Offer #3995218828 from 76561198087242027 state changed: Active -> Canceled","level":"verbose","timestamp":"2020-04-14T16:07:06.097Z"}
{"offerId":"3995218828","state":6,"finishTime":null,"level":"debug","message":"Took unknown ms to process offer","timestamp":"2020-04-14T16:07:06.098Z"}
{"message":"Message sent to 76561198087242027: Ohh nooooes! The offer is no longer available. Reason: The offer has been active for a while.","level":"info","timestamp":"2020-04-14T16:07:06.101Z"}
{"message":"Checking account info","level":"debug","timestamp":"2020-04-14T16:08:00.834Z"}
{"message":"0 incoming offers (0 on hold), 0 outgoing offers (0 on hold)","level":"verbose","timestamp":"2020-04-14T16:09:03.082Z"}`

Version: 3.4.0

**Comment by Nicklason** [comment]
I doubt it has anything to do with the bot failing to accept mobile confirmation
