### ISSUE TITLE
Bot Crashes 

### ISSUE THREAD

**Issue by asia-n** [Nicklason/tf2-automatic#424]
**Describe the bug**

**To Reproduce**

1.Let Bot run
2. After x amount of trades crashes

**Expected behavior**

Bot Crashes but doesnt restart properly

**Screenshots and logs**

Version: 3.4.0; node: v12.16.1 linux x64
[error.log](https://github.com/Nicklason/tf2-automatic/files/4478029/error.log)
[trade.log](https://github.com/Nicklason/tf2-automatic/files/4478030/trade.log)
[2020-04-14.log.gz](https://github.com/Nicklason/tf2-automatic/files/4478033/2020-04-14.log.gz)

**Additional context**

Im probably just stupid :)

**Comment by Nicklason** [comment]
Update to v3.5.0 and let me know if you get the error again. I am pretty sure it was fixed.

**Comment by asia-n** [comment]
If it doesn't crash again, i close it.

**Comment by asia-n** [comment]
no crash so i guess it's already fixed :)
