### ISSUE TITLE
keeps crashing on startup?

### ISSUE THREAD

**Issue by kerbster** [Nicklason/tf2-automatic#427]
**Describe the bug**

The cmd opens for a split second then closes continually until i stop the program. It continually writes to the error logs unless i close it.

**To Reproduce**

1. open the program from cmd or bat file using pm2 start tf2-automatic or pm2 start ecosystem.json

**Screenshots and logs**

[kerbster_crushbot.error.log](https://github.com/Nicklason/tf2-automatic/files/4500069/kerbster_crushbot.error.log)

[kerbster_crushbot-2020-04-19.log](https://github.com/Nicklason/tf2-automatic/files/4500070/kerbster_crushbot-2020-04-19.log)

Version: 3.5.1

**Comment by Floyd387** [comment]
Browsing the log I can see the following line: "Unknown SteamID input format \"<steamid of person to keep in friendslist>" ...
Check your ecosystem.json and see if you've filled the "Keep" line properly. You should add a SteamID64 ..Should be something like this:
"KEEP": ["76561198000091310"],
