### ISSUE TITLE
Autopricer doesn't work for all the items.

### ISSUE THREAD

**Issue by EliteOneTube** [Nicklason/tf2-automatic#428]
**Describe the bug**

**To Reproduce**

1. Add an item(For example !add sku=666;6) 
2. Close the bot and change the time of that item to 0 and the price to 0
3. Start the bot again and that item wont be affected by the autopricer.

**Expected behavior**

Version: 3.5.1

**Comment by aethezxd** [comment]
I mean, it's not really a "bug" since you are changing it's time which normally isn't changed by an ordinary user.

**Comment by EliteOneTube** [comment]
> I mean, it's not really a "bug" since you are changing it's time which normally isn't changed by an ordinary user.

Well It doesnt change the price too when you change it manual. Also it wont work even if the prices change on prices.tf

**Comment by Nicklason** [comment]
> I mean, it's not really a "bug" since you are changing it's time which normally isn't changed by an ordinary user.

It is a bug because the bot can't update the prices using the pricestf pricelist
