### ISSUE TITLE
[ TypeScript ] Suspicious expression, checks the truthyness of a function that returns a bool

### ISSUE THREAD

**Issue by lexidor** [Nicklason/tf2-automatic#430]
**Describe the bug**

Typescirpt complains here if you turn on some stricter nullchecks.
I believe this code is not doing what it should be doing.

https://github.com/Nicklason/tf2-automatic/blob/master/src/classes/UserCart.ts#L39
```TS
if ((this.bot.handler as MyHandler).hasDupeCheckEnabled) {
  // ...
}
```

**To Reproduce**

1. Turn on `strictNullChecks` in tsconfig.json
2. Visit UserCart.ts
3. Tead the following error message.

```
ts(2774)
This condition will always return true since the function is always defined.
Did you mean to call it instead?
```

**Expected behavior**
Call the function.

Version: 86f1e2f30422509c19fd4f3479e7db4ea092a8a9

**Comment by Nicklason** [comment]
Thanks 👍

**Comment by Nicklason** [comment]
https://github.com/Nicklason/tf2-automatic/commit/38f7d47a35bcceaf66aae41e51c88061df7a9d00
