### ISSUE TITLE
Possible escrow check issue. Check occured and gave an ok despite acceptescrow == false.

### ISSUE THREAD

**Issue by HunionKnight** [Nicklason/tf2-automatic#434]
**Describe the bug**
From ! Jerseyetr 's bot.
The bot performed an escrow check on a trade and did not reject despite acceptescrow == false.

**To Reproduce**

Steps to reproduce the behavior: Unknown reproduction method.

**Expected behavior**
Escrow checks on all trades. If err or escrow=true => reject. Code looks fine;

 checkEscrow(offer: TradeOfferManager.TradeOffer): Promise<boolean> {
        log.debug('Checking escrow');

        return new Promise((resolve, reject) => {
            const operation = retry.operation({
                retries: 5,
                factor: 2,
                minTimeout: 1000,
                randomize: true
            });

            operation.attempt(() => {
                log.debug('Attempting to check escrow...');
                offer.getUserDetails((err, me, them) => {
                    log.debug('Escrow callback');
                    if (!err || err.message !== 'Not Logged In') {
                        // No error / not because session expired
                        if (operation.retry(err)) {
                            return;
                        }

                        if (err) {
                            return reject(operation.mainError());
                        }

                        log.debug('Done checking escrow');

                        return resolve(them.escrowDays !== 0);
                    }

**Screenshots and logs**

Text log:
https://pastebin.com/YekBLRkC

**Additional context**

Please refer to @! jerseyetr for more information.

Version: 3.4.0

**Comment by Jerseyetr** [comment]
Happened again yesterday.

I'm at work and just now noticed.

I'll post logs here if I can.

Running latest version.
