### ISSUE TITLE
Bot does not retry to accept offer after encountered an error

### ISSUE THREAD

**Issue by idinium96** [Nicklason/tf2-automatic#437]
**Describe the bug**
My bot received an offer and then it encountered an error (28 - [Already redeemed](https://steamerrors.com/28)) and does not retry to accept it.
The offer was received at 2020-04-29T18:41:07.675Z and luckily the trade partner was someone with high patient and did not cancel the trade until I realized it at 2020-04-30T00:20:33.651Z (about 6+ hours), which I manually accept the trade and do the confirmation using my SDA. It seems that the trade was recorded in polldata as 'active' but it just ignores it, restarting the bot won't help either.

**To Reproduce**
_No known steps to reproduce an error._

**Expected behavior**
The bot should retry to accept the offer, even after the bot was restarted because that offer is still 'active' in polldata and it's not an invalid offer.

**Screenshots and logs**
Search for Offer ID #4020328414 in this log:
[Nezuko-2020-04-30.log](https://github.com/Nicklason/tf2-automatic/files/4555567/idin30-2020-04-30.log)

**Additional context**
N/A

Version: v3.5.2 (customized - but not related to this)

**Comment by aethezxd** [comment]
28 means that its already accepted.

**Comment by idinium96** [comment]
Yes, but the trade is still active at that moment. Please take a look at the log and search for the offer ID that I've mentioned.
Search it until there's no more of that offer ID.

**Comment by idinium96** [comment]
Another scenario (highlighted green)
[queue and ignored trade.docx](https://github.com/Nicklason/tf2-automatic/files/4567193/queue.and.ignored.trade.docx)
