### ISSUE TITLE
enable manual auto bump for premium

### ISSUE THREAD

**Issue by serzak51** [Nicklason/tf2-automatic#441]
**Is your feature request related to a problem? Please describe.**
 i have noticed when i tried to put a bot on my alt who don't have backpack.tf premium accoun, it was saying that there was a manual autobump feature enabled. but my question is: why there are manual autobump for non-premium user, but not for premium user? and it's not like premium autobump disable manual autobump, we can manual bump and autobump, so why?

**Describe the feature you'd like**
 simply enable manual autobump for premium user, with a waiting time of 45 minutes, then it manual autobump every 30 minutes(the first 45 minutes is because we can't manual bump 30 minute after that the listings was posted, and if we was bumping at 30 minute, the manual autobump would be erased by the premium autobump, so 45 minute is the perfect time. and then 30 minute because if we was continuing at 45 minute, one time it will work perfectly, but the other there will just be the premium autobump)

**Comment by Zeckatz** [comment]
If you have backpack.tf premium, it'll automatically bump your listings every 30 min. Why forcefully bump it when there is no reason for it?......

**Comment by serzak51** [comment]
yeah, but when we auto-bump with premium, we can always re-list. and because re-list count as a bump, if we combine auto-bump + auto re-list , it will make a bump every 15 minutes

**Comment by idinium96** [comment]
That will violate backpack.tf rules. So, no.
https://forums.backpack.tf/topic/53663-guide-for-reporting-on-the-main-site/?tab=comments#comment-601157

**Comment by serzak51** [comment]
oh, ok. i didn't knew
