### ISSUE TITLE
Being able to make your bot advertise in trade.tf

### ISSUE THREAD

**Issue by someone-random1** [Nicklason/tf2-automatic#450]
I would like that the tf2-automatic bots would be able to make advertisments in the site trade.tf for more chances of your items being bought instead of just advertising on backpack.tf

**Comment by danocmx** [comment]
As far as I'm aware trade.tf does not allow advertising on it's own, it only searches other community sites like backpack.tf, bazaar.tf, etc. Trade.tf also doesn't provide any API which would making any listings be pain in the ass, and it is unlikely any collaborator would want to spend time on this when there are better suggestions.
