### ISSUE TITLE
The bot cancels the trade after being "active for a while" even though it was active for only 18 seconds

### ISSUE THREAD

**Issue by someone-random1** [Nicklason/tf2-automatic#451]
Someone sent a trade to my bot and after 18 seconds of the trade offer being open the bot  cancels it for being active for a while (if there is a way to change this to 1 minute then please tell me)

1. send a trade offer to your bot
2. then wait 18 seconds or a bit longer
3. and see if it cancels the offer for being active for a while
-->

Should cancel the trade if it's open for more then 1 minute and not 18 seconds

Version: 3.5.2
![sasd](https://user-images.githubusercontent.com/66572183/84710684-60e2e500-af6d-11ea-8d96-f1d980610fe5.PNG)

**Comment by aethezxd** [comment]
If you have SDA (Steam Desktop Authenticator) open while your bot is on you might want to close it fully. If I remember correctly your SDA is polling data from Steam all the time which eventually leads into the "bug" you have occurring.

**Comment by idinium96** [comment]
Welp... I don't think that's the main issue. I don't have my SDA opened at all but this problem occurred anyway. I always run `pm2 logs` then I am using my computer and when I was that thing happened, it triggered me to do some check on the coding, but I think it's most likely a problem with Steam or some module related to Steam. Idk I am just guessing.

This screenshot showed that the trade got canceled just 13k ms (13 seconds) after it's being processed. It also can get to only 8k ms (8 seconds).
![canceled](https://user-images.githubusercontent.com/47635037/84776330-c210c400-b012-11ea-8905-d4f558c8697f.png)

**Comment by someone-random1** [comment]
My SDA is never open so I have no clue what the problem is, but this happens to someone else as well so I guess it's just needs fixing

**Comment by ZeusJunior** [comment]
I don’t think this is a bot issue, this happened on my main / to a few friends aswell when they tried to confirm the offer on their phones.
Offers just got canceled after confirming, both received and sent. 

I’m guessing it is something with steam

**Comment by Nicklason** [comment]
> I don’t think this is a bot issue, this happened on my main / to a few friends aswell when they tried to confirm the offer on their phones.
> Offers just got canceled after confirming, both received and sent.
> 
> I’m guessing it is something with steam

I think it has something to do with Steam returning an old response so that the steam-tradeoffer-manager module thinks that the offer is old, when it was just made.
