### ISSUE TITLE
I tried to put an item on my pricelist but it didn't work so I restarted my bot and now it's saying this error

### ISSUE THREAD

**Issue by someone-random1** [Nicklason/tf2-automatic#452]
Well I tried to put an item on my pricelist but it said "Expected JSON" so I restarted my bot and now it's saying this error
se description of what you expected to happen.

[sss.log](https://github.com/Nicklason/tf2-automatic/files/4799084/sss.log)
[ss.log](https://github.com/Nicklason/tf2-automatic/files/4799085/ss.log)

Version: 3.5.2

**Comment by Nicklason** [comment]
You're really quick haha. The API is not working right now, I am working on a fix.

**Comment by someone-random1** [comment]
Thanks, I guess?

**Comment by Nicklason** [comment]
> Thanks, I guess?

You're welcome?????? What kind of response is that

**Comment by someone-random1** [comment]
I don't know, should I just close this?

**Comment by Nicklason** [comment]
The API is back
