### ISSUE TITLE
[Linux] Fatal error on installing of modules

### ISSUE THREAD

**Issue by Goodgun123456789** [Nicklason/tf2-automatic#453]
Failure to build on Linux after running npm run build, tried the git and source code
https://transfer.sh/6bP9t/tsc-p..txt
https://transfer.sh/qWTHK/npm-debug.log
Any requested or related information will be delivered upon request

**Comment by idinium96** [comment]
You forgot to install modules:
https://github.com/Nicklason/tf2-automatic/wiki/Installation#installing-modules

**Comment by Goodgun123456789** [comment]
Thought the building of modules was installing, my mistake.  When building the modules it gives the provided errors

**Comment by Goodgun123456789** [comment]
Actually after running this, it isn't the same error.  My mistake (its 5 am over here, not in the soundest of minds right now).   Its an error with npm itself not working with the latest Linux kernal.  Sorry for the waste of time.
