### ISSUE TITLE
I am not sure what happened

### ISSUE THREAD

**Issue by someone-random1** [Nicklason/tf2-automatic#454]
I just started my bot and this bug happened

Version: 3.5.2
[yamyam1041.error.log](https://github.com/Nicklason/tf2-automatic/files/4834416/yamyam1041.error.log)
[yamyam1041-2020-06-26.log](https://github.com/Nicklason/tf2-automatic/files/4834417/yamyam1041-2020-06-26.log)
[yamyam1041.trade.log](https://github.com/Nicklason/tf2-automatic/files/4834418/yamyam1041.trade.log)

**Comment by idinium96** [comment]
Steam has updated profiles to have a new look, and things got broken.

You have to temporarily set `SKIP_UPDATE_PROFILE_SETTINGS` to `false` until the change in 7630257 is merged.

**Comment by someone-random1** [comment]
> Steam has updated profiles to have a new look, and things got broken.
> 
> You have to temporarily set `SKIP_UPDATE_PROFILE_SETTINGS` to `false` until the change in [7630257](https://github.com/Nicklason/tf2-automatic/commit/7630257e3b2b51066bc8c8254cdbf5946a2bce64) is merged.

How would I know when it comes back to normal?

**Comment by idinium96** [comment]
I have no clue.
