### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by lo8888** [Nicklason/tf2-automatic#455]
Describe the bug
The bot cannot log into Steam.

Log
1|Items  | 2020-07-01 01:16:25 debug: Got pricelist
1|Items  | 2020-07-01 01:16:25 info: Signing in to Steam...
1|Items  | 2020-07-01 01:16:25 debug: Starting login attempt {"loginKey":"xxxxxxxxxxxxxx+7A","private":true}
1|Items  | 2020-07-01 01:16:25 debug: Pricelist changed
1|Items  | 2020-07-01 01:16:25 debug: Signing in using login key
1|Items  | 2020-07-01 01:16:26 info: Signed in to Steam!
1|Items  | 2020-07-01 01:16:26 debug: Waiting for web session
1|Items  | 2020-07-01 01:16:27 debug: New login key
1|Items  | 2020-07-01 01:16:27 debug: New web session
1|Items  | 2020-07-01 01:16:27 info: Initializing bptf-listings...
1|Items  | 2020-07-01 01:16:27 debug: Getting inventory...
1|Items  | 2020-07-01 01:16:27 debug: Initializing bptf-listings...
1|Items  | 2020-07-01 01:16:27 debug: Updating profile settings...
1|Items  | Error: Malformed response
1|Items  |     at SteamCommunity.<anonymous> (/root/tf2-automatic/node_modules/steamcommunity/components/profile.js:166:14)
1|Items  |     at Request._callback (/root/tf2-automatic/node_modules/steamcommunity/components/http.js:67:15)
1|Items  |     at Request.self.callback (/root/tf2-automatic/node_modules/request/request.js:185:22)
1|Items  |     at Request.emit (events.js:321:20)
1|Items  |     at Request.<anonymous> (/root/tf2-automatic/node_modules/request/request.js:1161:10)
1|Items  |     at Request.emit (events.js:321:20)
1|Items  |     at Gunzip.<anonymous> (/root/tf2-automatic/node_modules/request/request.js:1083:12)
1|Items  |     at Object.onceWrapper (events.js:427:28)
1|Items  |     at Gunzip.emit (events.js:333:22)
1|Items  |     at endReadableNT (_stream_readable.js:1201:12)
1|Items  |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
1|Items  | 2020-07-01 01:16:29 error: tf2-automatic failed to start properly, this is most likely a temporary error. See the log:
1|Items  | package.version: 3.5.2; node: v13.9.0 linux x64}
1|Items  | Stack trace:
1|Items  | Error: Malformed response
1|Items  |     at SteamCommunity.<anonymous> (/root/tf2-automatic/node_modules/steamcommunity/components/profile.js:166:14)
1|Items  |     at Request._callback (/root/tf2-automatic/node_modules/steamcommunity/components/http.js:67:15)
1|Items  |     at Request.self.callback (/root/tf2-automatic/node_modules/request/request.js:185:22)
1|Items  |     at Request.emit (events.js:321:20)
1|Items  |     at Request.<anonymous> (/root/tf2-automatic/node_modules/request/request.js:1161:10)
1|Items  |     at Request.emit (events.js:321:20)
1|Items  |     at Gunzip.<anonymous> (/root/tf2-automatic/node_modules/request/request.js:1083:12)
1|Items  |     at Object.onceWrapper (events.js:427:28)
1|Items  |     at Gunzip.emit (events.js:333:22)
1|Items  |     at endReadableNT (_stream_readable.js:1201:12)
1|Items  |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
1|Items  | 2020-07-01 01:16:29 debug: Shutdown has been initialized, stopping... {"err":{}}
1|Items  | 2020-07-01 01:16:29 debug: Handler finished cleaning up
1|Items  | 2020-07-01 01:16:29 debug: Waiting for files to be saved
1|Items  | 2020-07-01 01:16:29 debug: Done waiting for files
1|Items  | 2020-07-01 01:16:29 warn: Exiting...

version: 3.5.2

**Comment by Gobot1234** [comment]
You need to update

**Comment by lo8888** [comment]
Isn't 3.5.2 the latest version? I tried the wiki method to update and it said it is up to date

**Comment by ZeusJunior** [comment]
If this issue is still happening, its because steam changed their edit profile settings.
Running `npm install steamcommunity --save` will fix this
