### ISSUE TITLE
Bot cannot buy wildcard unusuals

### ISSUE THREAD

**Issue by Doomguy46** [Nicklason/tf2-automatic#456]
**Describe the bug**

 Now it by all means should. The bot can list them and they are on the tf2-automatic GUI. But whenever an offer is sent it's held for manual review. This has lead me to miss out on four deals overnight, simply because I am asleep. I then have to manually put it up for sale despite specifying sale price. I've been told the issue is it counts it as unpriced, even though I have specified a price.

**To Reproduce**

1. Use the tf2-automatic GUI to set a price on an unusual, taunt, hat, etc. make sure to not specify effect
2. Restart the bot and wait for it to put up buy order.
3. Send a bot a trade offer for exactly what it's looking for and you'll find it's been held for manual review.

**Expected behavior**

I fully expected the bot to buy and sell items based on the prices I'd set. 
**Screenshots and logs**

Here are screenshots of the trades, buy orders, and bot sending me messages
![image](https://user-images.githubusercontent.com/30536301/87438142-ca7a0180-c5b4-11ea-8a0e-abea0ea0d821.png)
![image](https://user-images.githubusercontent.com/30536301/87438185-d796f080-c5b4-11ea-9045-fc6cf1f73176.png)
![image](https://user-images.githubusercontent.com/30536301/87438329-00b78100-c5b5-11ea-9f3e-2ac50a3d4c6c.png)

**Additional context**

Version: 3.5.2

**Comment by Zeckatz** [comment]
It's not a bug, it s a feature that hasn't been added, YET.

**Comment by idinium96** [comment]
duplicate #117

**Comment by Doomguy46** [comment]
ok my bad guess ill close this then
