### ISSUE TITLE
When I try to run the bot it says missing steam_account_name, but i filled out the notepad completely and named it ecosystem.json

### ISSUE THREAD

**Issue by RacerW123** [Nicklason/tf2-automatic#460]
![image](https://user-images.githubusercontent.com/64375597/90784761-74386680-e2b6-11ea-8dfd-aa5fdc44747c.png)

**Comment by aethezxd** [comment]
The ecosystem file is used when you launch it via PM2. Right now you seem to have done ``node dist/app.js`` which uses the .env file, so try filling that one instead.

**Comment by RacerW123** [comment]
> The ecosystem file is used when you launch it via PM2. Right now you seem to have done `node dist/app.js` which uses the .env file, so try filling that one instead.

Ok I'll try this!

**Comment by RacerW123** [comment]
Any idea what this means? I did it as you said @aethezxd 
![image](https://user-images.githubusercontent.com/64375597/90786307-47854e80-e2b8-11ea-92c3-12b31fbd2b47.png)

**Comment by aethezxd** [comment]
Yes. https://github.com/Nicklason/tf2-automatic/wiki/Errors#access-denied

If you would have read the wiki you wouldn't have had to stumble upon these "errors".
