### ISSUE TITLE
I don't understand how to add an item to my bot

### ISSUE THREAD

**Issue by RacerW123** [Nicklason/tf2-automatic#461]
I try to !add an item but it doesn't work it just says missing item properties, and I tried it multiple times in different ways. Thanks for the help!

**Comment by Zeckatz** [comment]
This isn't really answering your question but i suggest you to use https://github.com/ZeusJunior/tf2-automatic-gui
It's easy to add, update items using this (the gui)

And you should join the join the discord server.

**Comment by RacerW123** [comment]
Ok thank you, I'll check it out!
