### ISSUE TITLE
Recieved error "TypeError: Cannot read property 'concat' of null"

### ISSUE THREAD

**Issue by Fdert0** [Nicklason/tf2-automatic#463]
**Describe the bug**

  Got the error in console when trying to run the bot for the first time.

**To Reproduce**

1. Open cmd (standard perms)
2. Download bot using git to the desktop
2. Install latest TypeScript version
3. Install dependencies and fix audit errors
4. Compile the source
5. Create .env file with only the 4 required variables 'STEAM_ACCOUNT_NAME','STEAM_PASSWORD','STEAM_SHARED_SECRET','STEAM_IDENTITY_SECRET'
6. Try to run bot using node dist/app.js

**Expected behavior**
Bot to run successfully.

**Screenshots and logs**
![image](https://user-images.githubusercontent.com/71247293/93046959-3ca8aa00-f629-11ea-983b-92e01e4b8796.png)
[fdert13-2020-09-14.log](https://github.com/Nicklason/tf2-automatic/files/5216298/fdert13-2020-09-14.log)

**Additional context**
Running Windows 10 2004

Version: 3.5.2

**Comment by ZeusJunior** [comment]
I've made a wiki entry about this error [here](https://github.com/Nicklason/tf2-automatic/wiki/Errors#cannot-read-property-concat-of-null).
Originally this one was not added as this only appeared when people updated from V2 from V3, which was released some months ago.

You need to have the `ADMINS` and `KEEP` options, and they need to be an array with a valid steamid. Ex: `["76561198144346135"]`
