### ISSUE TITLE
Error message when testing out bot

### ISSUE THREAD

**Issue by Mardy321** [Nicklason/tf2-automatic#473]
There is an error when I type in 'node dist/app.js'

Seen a similar issue months back but now its happening to me
Pretty sure my identity and shared secret is accurate.

Help will be appreciated!

2020-11-28 02:07:53 info: Getting TF2 schema...
2020-11-28 02:07:57 info: Starting bot...
2020-11-28 02:07:57 info: Setting up pricelist...
2020-11-28 02:08:00 info: Signing in to Steam...
2020-11-28 02:08:02 error: tf2-automatic failed to start properly, this is most
likely a temporary error. See the log:
package.version: 3.5.2; node: v14.15.0 win32 x64}
Stack trace:
Error: Too many wrong Steam Guard codes
    at Bot.onSteamGuard (C:\Users\user\desktop\tf2-automatic\dist\classes\Bot.js
:554:19)
    at Immediate.<anonymous> (C:\Users\user\desktop\tf2-automatic\dist\classes\B
ot.js:142:21)
    at processImmediate (internal/timers.js:461:21)
2020-11-28 02:08:02 warn: Exiting...

**Comment by Gobot1234** [comment]
You're shared_secret is probably wrong

**Comment by Mardy321** [comment]
@Gobot1234 

Its correct tho. I just re-added the identity and shared secret just to make sure. The same error pops up again.

**Comment by Mardy321** [comment]
Im not sure if this is the reason but I am doing all of this in a new account, so my 7 day restriction hasn't been lifted. Could that be the case why I am getting that error?

**Comment by ctrl-duck** [comment]
im getting the same errors and my acc is 16 days active since i activated sda and also unlimited,
im also sure that i did n t make errors in the .env

**Comment by Mardy321** [comment]
@ctrl-duck 

My account will be 15 days active tomorrow. 

Ill see whether the same issue pops up for me still.

**Comment by ctrl-duck** [comment]
- i fixxed my bot, if tomorrow u ll need help reply at this comment 😃

**Comment by ctrl-duck** [comment]
@Mardy321

**Comment by Mardy321** [comment]
@ctrl-duck  Oh nice!. I will make sure to reach out for your help if I do come across the same error again

**Comment by Mardy321** [comment]
@ctrl-duck  

My 15 days have passed. My bot is now tradable. 
Im still getting this error. ._.


What did you do to fix it?

**Comment by ctrl-duck** [comment]
@Mardy321 my mistake was the .env, make sure u checked the square in ur file browser wich allows to see the file type like .txt .bat,be sure that u renamed .env because mine was .env.env after i setted visible file types.
then my second error was the unfilled groups, leave it the original groups id numbers,also dont leave blank admin and keep,after these changes my bot started working

**Comment by ctrl-duck** [comment]
GROUPS=["103582791464047777","103582791462300957"]

**Comment by ctrl-duck** [comment]
https://www.howtogeek.com/205086/beginner-how-to-make-windows-show-file-extensions/ 
this is the link from original wiki for how to see file extension

**Comment by Mardy321** [comment]
Still not working for me. :(  Im getting the same error. 

My .eve file is named correct and I filled in the groups.

My SDA says invalid authenticator when I press 'view confirmations'
I was thinking that could be the issue

Is SDA working fine on your side?

**Comment by ctrl-duck** [comment]
open sda and find "refresh login"

**Comment by ctrl-duck** [comment]
did it appeared a folder called files? wich contains a folder called as ur steam login, if there is the folder try to delete polldata.json and run it again

**Comment by ctrl-duck** [comment]
i just noticed this now! im using tf2autobot, it s an updated version of tf2automatic, u should try it maybe it ll solve the problem

**Comment by ctrl-duck** [comment]
i took another look at ur console log upthere, i think the problem is SDA try to refresh the login (it ll look like the app ll exit from SG codes but it wont, it just update login info without exit from SG codes)

**Comment by ctrl-duck** [comment]
SG codes keeps going if u change password on SDA, SG codes also keeps going even in the mobile app when u log out

**Comment by Mardy321** [comment]
Hmm. I'll try using autobot. Maybe that'll solve it!

**Comment by Mardy321** [comment]
I tried logging in again for SDA but to no avail

**Comment by ctrl-duck** [comment]
mhm... if u have got the folder called files delete polldata.json
if not, be sure file esxtension is enabled in ur file browser.
if the bot never created a folder called files, try to start everything again. 
after the download commands git clonde and typescript, now do npm install and wait what the console print on the log, if it writes npm audit fix, run the command and it ll fix missing pieces (i think im not sure), i hope this gonna work 😃

**Comment by ctrl-duck** [comment]
if it ll keep exiting, just reply again 😃

**Comment by ctrl-duck** [comment]
@Mardy321

**Comment by Mardy321** [comment]
@ctrl-duck 

In my files there is only loginattempts.json and options.json

**Comment by Mardy321** [comment]
I switched to tf2 autobot and now a similar error pops up regarding the steam guard codes again 


 You are not running the bot with PM2! If the bot crash
es it won't start again. Get a VPS and run your bot with PM2: https://github.com
/idinium96/tf2autobot/wiki/Getting-a-VPS
2020-12-14 15:28:03 debug: Connecting to PM2...
2020-12-14 15:28:03 info: Getting TF2 schema...
2020-12-14 15:28:10 info: Starting bot...
2020-12-14 15:28:10 debug: Calling onRun
2020-12-14 15:28:10 debug: Setting login attempts
2020-12-14 15:28:10 info: Setting up pricelist...
2020-12-14 15:28:10 debug: Getting key prices...
2020-12-14 15:28:11 debug: Got key price
2020-12-14 15:28:11 debug: Key rate is set based current key prices. {"buy":{"ke
ys":0,"metal":61.66},"sell":{"keys":0,"metal":62.22},"src":"ptf","time":16079108
76}
2020-12-14 15:28:11 info: Signing in to Steam...
2020-12-14 15:28:11 debug: Starting login attempt
2020-12-14 15:28:11 debug: Signing in using password
2020-12-14 15:28:11 debug: Steam guard code requested
2020-12-14 15:28:13 debug: Steam guard code requested
2020-12-14 15:28:13 debug: Steam guard code requested
2020-12-14 15:28:13 error: TF2Autobot failed to start properly, this is most lik
ely a temporary error. See the log:
package.version: 2.3.1; node: v14.15.0 win32 x64}
Stack trace:
Error: Too many wrong Steam Guard codes
    at Bot.onSteamGuard (C:\Users\user\desktop\tf2autobot\dist\classes\Bot.js:57
1:19)
    at Immediate.<anonymous> (C:\Users\user\desktop\tf2autobot\dist\classes\Bot.
js:164:21)
    at processImmediate (internal/timers.js:461:21)
2020-12-14 15:28:13 debug: Shutdown has been initialized, stopping... {"err":"un
caughtException"}
2020-12-14 15:28:13 debug: Handler finished cleaning up
2020-12-14 15:28:13 debug: Waiting for files to be saved
2020-12-14 15:28:13 debug: Done waiting for files
2020-12-14 15:28:13 warn: Exiting...

**Comment by ctrl-duck** [comment]
have u tryed to drag out the folder and start it wout the folder inside?
this can may work

**Comment by Mardy321** [comment]
@ctrl-duck 

Nope. How do I do that?

**Comment by ctrl-duck** [comment]
drag files onto ur desktop

**Comment by ctrl-duck** [comment]
u can delete too if u want the bot ll create another one

**Comment by ctrl-duck** [comment]
u can drag out if u already edited option.json and u want to backup it

**Comment by ctrl-duck** [comment]
have u ever moved sda folder?

**Comment by ctrl-duck** [comment]
maybe the bot cant find the sda direcrory if u moved it

**Comment by Mardy321** [comment]
I dont think I moved the SDA folder.

But just in case, where is it supposed to be located at?

**Comment by ctrl-duck** [comment]
i ve the folder on my desktop, but i think u can place wherever you want

**Comment by ctrl-duck** [comment]
does sda allows u to check confirmatios or it shows an error message?

**Comment by Mardy321** [comment]
It doesnt. 

When i click 'view confirmations' it gives me this error 

![steam authenticator (2)](https://user-images.githubusercontent.com/75129865/102054981-22978700-3e25-11eb-9978-a787135e1845.PNG)

**Comment by Mardy321** [comment]
Im sure my timezones on mobile and pc are correct

**Comment by Mardy321** [comment]
This should be the issue here. Im tryna look up on how i can solve this issue

**Comment by ctrl-duck** [comment]
did u enabled encryption key on Sda? idk if this ll solve the problem

**Comment by Mardy321** [comment]
Nope. I heard there wasnt a need to but I will try it out.

**Comment by ctrl-duck** [comment]
take a look on sda issues too, i think u ll find the solution there

**Comment by ctrl-duck** [comment]
https://github.com/Jessecar96/SteamDesktopAuthenticator

**Comment by Mardy321** [comment]
Yup. I actually put my error there a few days back. 

Ill try and find a solution. Thanks for all the help by the way. Ill leave a reply when i finally fixed my bot :D

**Comment by ctrl-duck** [comment]
today my bot crashed and it didn't started again due to dont having a vps and pm2, because i run it in windows, but i deleted the folder named as <steam account> inside the folder "files", after i deleted the folder into "files" it runned again,
(u ll need this in future) copy what s typed into options.json and pricelist.json for backup them if u edited them. 
i hope u ll fix it as soon as possible :D
