### ISSUE TITLE
Bot does not retry accepting offers from owner

### ISSUE THREAD

**Issue by Anton-Beresansky** [Nicklason/tf2-automatic#65]
`24-10-2018 02:23:16 - info: Offer #3345850737 received from 76561198020822150`
`24-10-2018 02:23:16 - info: Offer #3345850737 is from an owner, accepting`
`24-10-2018 02:23:16 - info: Message sent to M_SERVER ✅ trade.tf (76561197994727567): Offer from owner, accepting`
`24-10-2018 02:23:17 - warn: Offer #3345850737 could not be accepted: Not Logged In`
Of course would be great if bot could accept **every** offer, but if we have this bug, please, make bot retry to accept the offer after he refresh the session. Thanks

**Comment by Nicklason** [comment]
#98
