### ISSUE TITLE
Bot creates an offer with metal even though there are enough keys

### ISSUE THREAD

**Issue by Anton-Beresansky** [Nicklason/tf2-automatic#66]
`!price buzz`
`M_BOT: I am buying a The Buzz Killer for 20 ref and selling for 1 key. I have 2 / 1 (last updated 08-11-2018 23:26:46 +0000).`
`M_SERVER ✅ trade.tf: !buy The Buzz Killer`
`M_BOT: Please wait while I process your offer! You will be offered 1 The Buzz Killer for your 1 key.`
`Your offer has been made, please wait while I accept the mobile confirmation.`
And I get an offer:
`New offer #3362178254 from M_BOT. They offer: The Buzz Killer for my 39.89 metal`

**Comment by Aethezxd** [comment]
"Feature"

**Comment by Aethezxd** [comment]
JK

**Comment by Anton-Beresansky** [comment]
I don't understand.

**Comment by Nicklason** [comment]
I'd assume this is a problem with the way the bot was giving change, the algorithm has been changed and should therefore be fixed.
