### ISSUE TITLE
Bot accepted more items than it should have

### ISSUE THREAD

**Issue by Senakhtenre** [Nicklason/tf2-automatic#72]
Hi there!

My bot has recently sent a trade that I believe shouldn't have because the purchased items would exceed the defined stock. This happened with the !sell command, cannot confirm if this happens also via trade offer.

Reply of the bot to the !price command (as you can see, stock was set to two): I am buying a Battle-Worn Robot Taunt Processor for 0.55 ref and selling for 0.66 ref. I have 23 / 2 (last updated 05-12-2018 14:19:43 +0000).
Trade: https://tf2automatic.com/trades?id=5c08417bd990a12e9785862a

05-12-2018 11:20:57 - info: Message from Scuram (76561198146073716): !sell 23 Battle-Worn Robot Taunt Processor
05-12-2018 11:20:57 - debug: Adding requested offer to queue
05-12-2018 11:20:57 - debug: Found an offer in the queue, processing it now.
05-12-2018 11:20:57 - info: Handling requested offer from 76561198146073716
05-12-2018 11:20:59 - info: Message sent to Scuram (76561198146073716): Please wait while I process your offer! You will be offered 12.77 ref for your 23 Battle-Worn Robot Taunt Processor(s).

I believe this happened also to other tf2automatic owners and was forwarded on Discord but I've decided to report it here to make it easier to spot rather than on channels logs.

**Comment by Nicklason** [comment]
The problem has been fixed, thank you for making an issue - https://github.com/Nicklason/tf2-automatic/pull/73
