### ISSUE TITLE
Add command to stop the bot

### ISSUE THREAD

**Issue by kebaburmum** [Nicklason/tf2-automatic#76]
Please add !shutdown command, so maybe if the owner has many outdated listings, cannot update them and isnt home to turn off the bot

**Comment by kebaburmum** [comment]
or when u dont have time to update all the listings

**Comment by kebaburmum** [comment]
so u will shut it down if u not home thru command and than do it at home

**Comment by Nicklason** [comment]
Thank you for making an issue! I'll add this in a few minutes 😄

**Comment by Nicklason** [comment]
Clicked the wrong button

**Comment by kebaburmum** [comment]
lol i tried to add it for like 2 hrs lol gotta learn

**Comment by Nicklason** [comment]
It is literally one function that needs to be called, I'll finish what I am working on and add it 😃

**Comment by kebaburmum** [comment]
I know but im learning node.js by seeing other projects and copying it and experimenting with it lol

**Comment by Nicklason** [comment]
Added with version 1.10.9
