### ISSUE TITLE
Add a option to enable/disable screenshots in the config.json

### ISSUE THREAD

**Issue by ghost** [Nicklason/tf2-automatic#79]
Idk something like  "screenshots":true/false;

if (screenshots:true)
Automatic.Screenshot some shit

else
//Automatic.Screenshot some shit (dont)

**Comment by Thecloudbacon** [comment]
Please do this, it’d be easier to have this in the system instead of having to change code.
It should also have an option to change screenshots into text saying what was bought/sold

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Nicklason** [comment]
Screenshots are removed in v2
