### ISSUE TITLE
Make the Bot bump only active listings

### ISSUE THREAD

**Issue by kebaburmum** [Nicklason/tf2-automatic#82]
Well its really when i have buy orders for 50+ unusual taunts but I want to buy unique things but have pure enough for them. It would be cool if i dont have to force remove them all, please add this asap

**Comment by kebaburmum** [comment]
Otherwise i cant trade

**Comment by kebaburmum** [comment]
high priority

**Comment by Waflson** [comment]
https://github.com/Nicklason/tf2-automatic/issues/168 Duplicated feature request
