### ISSUE TITLE
Send message with the items and value in a trade instead of screenshot

### ISSUE THREAD

**Issue by kebaburmum** [Nicklason/tf2-automatic#83]
yeah so i dont have open another browser and check manually

**Comment by Thecloudbacon** [comment]
You could do this instead of screenshots xd

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Zayonx** [comment]
Something better would be to send a screenshot of the trade on steam, and if the screenshot fails then do this.

**Comment by Nicklason** [comment]
Done in v2
