### ISSUE TITLE
Bot randomly selects owner to be removed

### ISSUE THREAD

**Issue by DaSimple619** [Nicklason/tf2-automatic#85]
https://cdn.discordapp.com/attachments/286198710046818304/519574946830221312/unknown.png

**Comment by Thecloudbacon** [comment]
Add your id in “friends to not be removed” or something like that in config.js

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Nicklason** [comment]
Fixed with https://github.com/Nicklason/tf2-automatic/pull/87
