### ISSUE TITLE
Option to disallow overpay

### ISSUE THREAD

**Issue by Senakhtenre** [Nicklason/tf2-automatic#86]
A small suggestion:

If possible it would be nice to have an option within the config file that would allow the bot owners to allow/disallow overpay on the bot trades.

**Comment by Senakhtenre** [comment]
> Hasn't it been removed completely a while ago?

I wouldn't say it has, I already had 2-3 players that overpaid for an item and I had to manually look up the logs/screens and refund so I think it is still possible for them to overpay.

> To prevent errors?

Human errors yes :P

**Comment by Nicklason** [comment]
Now that I think about it. When you say overpay, do you mean that people are offering items for your items? @Senakhtenre

**Comment by Senakhtenre** [comment]
> Now that I think about it. When you say overpay, do you mean that people are offering items for your items? @Senakhtenre

When someone offers me more for an item than the value I've asked for. Like I ask for 40ref and I'm given 42ref.

**Comment by Nicklason** [comment]
Added in v2 https://github.com/Nicklason/tf2-automatic/commit/6aadaf6c5410df68fad139535fcc5ae9e9719205
