### ISSUE TITLE
-1.66 profit????

### ISSUE THREAD

**Issue by Billason** [Nicklason/tf2-automatic#89]
nicklason this happened to me is it normal??
i lose 3.44
in last 2 days

**Comment by Billason** [comment]
nah just close it
becus price changes

**Comment by ZeusJunior** [comment]
If you buy an item and haven't sold it, yea

It happens, the profit command isn't the most accurate thing in the world

**Comment by Nicklason** [comment]
https://github.com/Nicklason/tf2-automatic/issues/88#issuecomment-448625418
