### ISSUE TITLE
not sure what the error is about

### ISSUE THREAD

**Issue by LELManiac** [Nicklason/tf2-automatic#92]
![sshelp](https://user-images.githubusercontent.com/25754855/51139665-2db69680-184d-11e9-89d8-e4e69ea9afdf.png)

**Comment by Nicklason** [comment]
You can’t use the latest version of node with the bot, you need to downgrade to an earlier version.

**Comment by LELManiac** [comment]
Should probably update some files about the installation then. 

> We'll download the newest version of NodeJS. Copy the block below and paste it into putty.

Stated in https://github.com/Nicklason/tf2-automatic/wiki/Setup-on-Linux#downloading-nodejs
