### ISSUE TITLE
Stock always=1

### ISSUE THREAD

**Issue by Anton-Beresansky** [Nicklason/tf2-automatic#95]
`[2:29]M:	!update name=Genuine Bonk Helm&stock=2`
`[2:29]M_BOT:	Updated Genuine Bonk Helm.`
`[2:29]M:	!price Genuine Bonk Helm`
`[2:29]M_BOT:	I am buying a Genuine Bonk Helm for 26 ref and selling for 1 key. I have 0 / 1 (last pdated 18-01-2019 00:29:26 +0000).`
`[2:31]M:	!update name=Genuine Bonk Helm&stock=4`
`[2:31]M_BOT:	Updated Genuine Bonk Helm.`
`[2:31]M:	!price Genuine Bonk Helm`
`[2:31]M_BOT:	I am buying a Genuine Bonk Helm for 26 ref and selling for 1 key. I have 0 / 1 (last pdated 18-01-2019 00:31:08 +0000).`

**Comment by Waflson** [comment]
Have you tried restarting the bot? Does it have the issue after you updated the item and then restarted it?

**Comment by Anton-Beresansky** [comment]
Lol, &limit=5
I need to sleep XD
